package com.pos.entity;

public class Apibusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apibusiness.fsbusinessno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsbusinessno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apibusiness.fsname
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apibusiness.fsdescribe
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsdescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apibusiness.fstoken
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fstoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apibusiness.fitest
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fitest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apibusiness.fshost
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fshost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apibusiness.fsseed
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsseed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apibusiness.fitimestamp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fitimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apibusiness.fsbusinessno
     *
     * @return the value of apibusiness.fsbusinessno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsbusinessno() {
        return fsbusinessno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apibusiness.fsbusinessno
     *
     * @param fsbusinessno the value for apibusiness.fsbusinessno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsbusinessno(String fsbusinessno) {
        this.fsbusinessno = fsbusinessno == null ? null : fsbusinessno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apibusiness.fsname
     *
     * @return the value of apibusiness.fsname
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsname() {
        return fsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apibusiness.fsname
     *
     * @param fsname the value for apibusiness.fsname
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsname(String fsname) {
        this.fsname = fsname == null ? null : fsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apibusiness.fsdescribe
     *
     * @return the value of apibusiness.fsdescribe
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsdescribe() {
        return fsdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apibusiness.fsdescribe
     *
     * @param fsdescribe the value for apibusiness.fsdescribe
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsdescribe(String fsdescribe) {
        this.fsdescribe = fsdescribe == null ? null : fsdescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apibusiness.fstoken
     *
     * @return the value of apibusiness.fstoken
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFstoken() {
        return fstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apibusiness.fstoken
     *
     * @param fstoken the value for apibusiness.fstoken
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFstoken(String fstoken) {
        this.fstoken = fstoken == null ? null : fstoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apibusiness.fitest
     *
     * @return the value of apibusiness.fitest
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFitest() {
        return fitest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apibusiness.fitest
     *
     * @param fitest the value for apibusiness.fitest
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFitest(Integer fitest) {
        this.fitest = fitest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apibusiness.fshost
     *
     * @return the value of apibusiness.fshost
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFshost() {
        return fshost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apibusiness.fshost
     *
     * @param fshost the value for apibusiness.fshost
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFshost(String fshost) {
        this.fshost = fshost == null ? null : fshost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apibusiness.fsseed
     *
     * @return the value of apibusiness.fsseed
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsseed() {
        return fsseed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apibusiness.fsseed
     *
     * @param fsseed the value for apibusiness.fsseed
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsseed(String fsseed) {
        this.fsseed = fsseed == null ? null : fsseed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apibusiness.fitimestamp
     *
     * @return the value of apibusiness.fitimestamp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFitimestamp() {
        return fitimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apibusiness.fitimestamp
     *
     * @param fitimestamp the value for apibusiness.fitimestamp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFitimestamp(Integer fitimestamp) {
        this.fitimestamp = fitimestamp;
    }
}