package com.pos.entity;

public class ApiflowingWithBLOBs extends Apiflowing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apiflowing.fstdata
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fstdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apiflowing.fserror
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fserror;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apiflowing.fsrdata
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsrdata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apiflowing.fstdata
     *
     * @return the value of apiflowing.fstdata
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFstdata() {
        return fstdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apiflowing.fstdata
     *
     * @param fstdata the value for apiflowing.fstdata
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFstdata(String fstdata) {
        this.fstdata = fstdata == null ? null : fstdata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apiflowing.fserror
     *
     * @return the value of apiflowing.fserror
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFserror() {
        return fserror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apiflowing.fserror
     *
     * @param fserror the value for apiflowing.fserror
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFserror(String fserror) {
        this.fserror = fserror == null ? null : fserror.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apiflowing.fsrdata
     *
     * @return the value of apiflowing.fsrdata
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsrdata() {
        return fsrdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apiflowing.fsrdata
     *
     * @param fsrdata the value for apiflowing.fsrdata
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsrdata(String fsrdata) {
        this.fsrdata = fsrdata == null ? null : fsrdata.trim();
    }
}