package com.pos.entity;

import java.math.BigDecimal;

public class Apipaymentdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fspayno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fspayno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fsorderid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fsshopguid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsshopguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fisourceid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fisourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fipaymenttypeid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fipaymenttypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fisettlementmerchant
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fisettlementmerchant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fitradetype
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fitradetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fipayee
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fipayee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fdamount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fssyspayid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fssyspayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fstradeno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fstradeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fsopenid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsopenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fstransuserid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fstransuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.alipayemail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String alipayemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fiisactive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiisactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fstradetime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fstradetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fscreatetime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fscreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fsupdatetime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fdamount1
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdamount1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fdextreceipt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdextreceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fssqe
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fssqe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fssellno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fssellno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fiReturnstate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiReturnstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fsdate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fscheckbillno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fscheckbillno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fibank_own
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fibank_own;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fdmeiweiFee
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdmeiweiFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fdthirdpartyFee
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdthirdpartyFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fdali_discount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdali_discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fdext_discount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdext_discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fsPayFinished
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsPayFinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apipaymentdetail.fspay_paytime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fspay_paytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fspayno
     *
     * @return the value of apipaymentdetail.fspayno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFspayno() {
        return fspayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fspayno
     *
     * @param fspayno the value for apipaymentdetail.fspayno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFspayno(String fspayno) {
        this.fspayno = fspayno == null ? null : fspayno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fsorderid
     *
     * @return the value of apipaymentdetail.fsorderid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsorderid() {
        return fsorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fsorderid
     *
     * @param fsorderid the value for apipaymentdetail.fsorderid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsorderid(String fsorderid) {
        this.fsorderid = fsorderid == null ? null : fsorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fsshopguid
     *
     * @return the value of apipaymentdetail.fsshopguid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsshopguid() {
        return fsshopguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fsshopguid
     *
     * @param fsshopguid the value for apipaymentdetail.fsshopguid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsshopguid(String fsshopguid) {
        this.fsshopguid = fsshopguid == null ? null : fsshopguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fisourceid
     *
     * @return the value of apipaymentdetail.fisourceid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFisourceid() {
        return fisourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fisourceid
     *
     * @param fisourceid the value for apipaymentdetail.fisourceid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFisourceid(Integer fisourceid) {
        this.fisourceid = fisourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fipaymenttypeid
     *
     * @return the value of apipaymentdetail.fipaymenttypeid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFipaymenttypeid() {
        return fipaymenttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fipaymenttypeid
     *
     * @param fipaymenttypeid the value for apipaymentdetail.fipaymenttypeid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFipaymenttypeid(Integer fipaymenttypeid) {
        this.fipaymenttypeid = fipaymenttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fisettlementmerchant
     *
     * @return the value of apipaymentdetail.fisettlementmerchant
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFisettlementmerchant() {
        return fisettlementmerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fisettlementmerchant
     *
     * @param fisettlementmerchant the value for apipaymentdetail.fisettlementmerchant
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFisettlementmerchant(Integer fisettlementmerchant) {
        this.fisettlementmerchant = fisettlementmerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fitradetype
     *
     * @return the value of apipaymentdetail.fitradetype
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFitradetype() {
        return fitradetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fitradetype
     *
     * @param fitradetype the value for apipaymentdetail.fitradetype
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFitradetype(Integer fitradetype) {
        this.fitradetype = fitradetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fipayee
     *
     * @return the value of apipaymentdetail.fipayee
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFipayee() {
        return fipayee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fipayee
     *
     * @param fipayee the value for apipaymentdetail.fipayee
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFipayee(Integer fipayee) {
        this.fipayee = fipayee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fdamount
     *
     * @return the value of apipaymentdetail.fdamount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdamount() {
        return fdamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fdamount
     *
     * @param fdamount the value for apipaymentdetail.fdamount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdamount(BigDecimal fdamount) {
        this.fdamount = fdamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fssyspayid
     *
     * @return the value of apipaymentdetail.fssyspayid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFssyspayid() {
        return fssyspayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fssyspayid
     *
     * @param fssyspayid the value for apipaymentdetail.fssyspayid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFssyspayid(String fssyspayid) {
        this.fssyspayid = fssyspayid == null ? null : fssyspayid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fstradeno
     *
     * @return the value of apipaymentdetail.fstradeno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFstradeno() {
        return fstradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fstradeno
     *
     * @param fstradeno the value for apipaymentdetail.fstradeno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFstradeno(String fstradeno) {
        this.fstradeno = fstradeno == null ? null : fstradeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fsopenid
     *
     * @return the value of apipaymentdetail.fsopenid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsopenid() {
        return fsopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fsopenid
     *
     * @param fsopenid the value for apipaymentdetail.fsopenid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsopenid(String fsopenid) {
        this.fsopenid = fsopenid == null ? null : fsopenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fstransuserid
     *
     * @return the value of apipaymentdetail.fstransuserid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFstransuserid() {
        return fstransuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fstransuserid
     *
     * @param fstransuserid the value for apipaymentdetail.fstransuserid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFstransuserid(String fstransuserid) {
        this.fstransuserid = fstransuserid == null ? null : fstransuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.alipayemail
     *
     * @return the value of apipaymentdetail.alipayemail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getAlipayemail() {
        return alipayemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.alipayemail
     *
     * @param alipayemail the value for apipaymentdetail.alipayemail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setAlipayemail(String alipayemail) {
        this.alipayemail = alipayemail == null ? null : alipayemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fiisactive
     *
     * @return the value of apipaymentdetail.fiisactive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiisactive() {
        return fiisactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fiisactive
     *
     * @param fiisactive the value for apipaymentdetail.fiisactive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiisactive(Integer fiisactive) {
        this.fiisactive = fiisactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fstradetime
     *
     * @return the value of apipaymentdetail.fstradetime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFstradetime() {
        return fstradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fstradetime
     *
     * @param fstradetime the value for apipaymentdetail.fstradetime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFstradetime(String fstradetime) {
        this.fstradetime = fstradetime == null ? null : fstradetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fscreatetime
     *
     * @return the value of apipaymentdetail.fscreatetime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFscreatetime() {
        return fscreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fscreatetime
     *
     * @param fscreatetime the value for apipaymentdetail.fscreatetime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFscreatetime(String fscreatetime) {
        this.fscreatetime = fscreatetime == null ? null : fscreatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fsupdatetime
     *
     * @return the value of apipaymentdetail.fsupdatetime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsupdatetime() {
        return fsupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fsupdatetime
     *
     * @param fsupdatetime the value for apipaymentdetail.fsupdatetime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsupdatetime(String fsupdatetime) {
        this.fsupdatetime = fsupdatetime == null ? null : fsupdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fdamount1
     *
     * @return the value of apipaymentdetail.fdamount1
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdamount1() {
        return fdamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fdamount1
     *
     * @param fdamount1 the value for apipaymentdetail.fdamount1
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdamount1(BigDecimal fdamount1) {
        this.fdamount1 = fdamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fdextreceipt
     *
     * @return the value of apipaymentdetail.fdextreceipt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdextreceipt() {
        return fdextreceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fdextreceipt
     *
     * @param fdextreceipt the value for apipaymentdetail.fdextreceipt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdextreceipt(BigDecimal fdextreceipt) {
        this.fdextreceipt = fdextreceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fssqe
     *
     * @return the value of apipaymentdetail.fssqe
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFssqe() {
        return fssqe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fssqe
     *
     * @param fssqe the value for apipaymentdetail.fssqe
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFssqe(String fssqe) {
        this.fssqe = fssqe == null ? null : fssqe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fssellno
     *
     * @return the value of apipaymentdetail.fssellno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFssellno() {
        return fssellno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fssellno
     *
     * @param fssellno the value for apipaymentdetail.fssellno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFssellno(String fssellno) {
        this.fssellno = fssellno == null ? null : fssellno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fiReturnstate
     *
     * @return the value of apipaymentdetail.fiReturnstate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiReturnstate() {
        return fiReturnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fiReturnstate
     *
     * @param fiReturnstate the value for apipaymentdetail.fiReturnstate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiReturnstate(Integer fiReturnstate) {
        this.fiReturnstate = fiReturnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fsdate
     *
     * @return the value of apipaymentdetail.fsdate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsdate() {
        return fsdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fsdate
     *
     * @param fsdate the value for apipaymentdetail.fsdate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsdate(String fsdate) {
        this.fsdate = fsdate == null ? null : fsdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fscheckbillno
     *
     * @return the value of apipaymentdetail.fscheckbillno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFscheckbillno() {
        return fscheckbillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fscheckbillno
     *
     * @param fscheckbillno the value for apipaymentdetail.fscheckbillno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFscheckbillno(String fscheckbillno) {
        this.fscheckbillno = fscheckbillno == null ? null : fscheckbillno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fibank_own
     *
     * @return the value of apipaymentdetail.fibank_own
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFibank_own() {
        return fibank_own;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fibank_own
     *
     * @param fibank_own the value for apipaymentdetail.fibank_own
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFibank_own(Integer fibank_own) {
        this.fibank_own = fibank_own;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fdmeiweiFee
     *
     * @return the value of apipaymentdetail.fdmeiweiFee
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdmeiweiFee() {
        return fdmeiweiFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fdmeiweiFee
     *
     * @param fdmeiweiFee the value for apipaymentdetail.fdmeiweiFee
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdmeiweiFee(BigDecimal fdmeiweiFee) {
        this.fdmeiweiFee = fdmeiweiFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fdthirdpartyFee
     *
     * @return the value of apipaymentdetail.fdthirdpartyFee
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdthirdpartyFee() {
        return fdthirdpartyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fdthirdpartyFee
     *
     * @param fdthirdpartyFee the value for apipaymentdetail.fdthirdpartyFee
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdthirdpartyFee(BigDecimal fdthirdpartyFee) {
        this.fdthirdpartyFee = fdthirdpartyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fdali_discount
     *
     * @return the value of apipaymentdetail.fdali_discount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdali_discount() {
        return fdali_discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fdali_discount
     *
     * @param fdali_discount the value for apipaymentdetail.fdali_discount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdali_discount(BigDecimal fdali_discount) {
        this.fdali_discount = fdali_discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fdext_discount
     *
     * @return the value of apipaymentdetail.fdext_discount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdext_discount() {
        return fdext_discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fdext_discount
     *
     * @param fdext_discount the value for apipaymentdetail.fdext_discount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdext_discount(BigDecimal fdext_discount) {
        this.fdext_discount = fdext_discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fsPayFinished
     *
     * @return the value of apipaymentdetail.fsPayFinished
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsPayFinished() {
        return fsPayFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fsPayFinished
     *
     * @param fsPayFinished the value for apipaymentdetail.fsPayFinished
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsPayFinished(String fsPayFinished) {
        this.fsPayFinished = fsPayFinished == null ? null : fsPayFinished.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apipaymentdetail.fspay_paytime
     *
     * @return the value of apipaymentdetail.fspay_paytime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFspay_paytime() {
        return fspay_paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apipaymentdetail.fspay_paytime
     *
     * @param fspay_paytime the value for apipaymentdetail.fspay_paytime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFspay_paytime(String fspay_paytime) {
        this.fspay_paytime = fspay_paytime == null ? null : fspay_paytime.trim();
    }
}