package com.pos.entity;

import java.math.BigDecimal;

public class Tbask extends TbaskKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbask.fsAskGpId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsAskGpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbask.fsAskName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsAskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbask.fdAddPrice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdAddPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbask.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbask.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbask.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbask.fiItemCd
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiItemCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbask.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbask.fsAskGpId
     *
     * @return the value of tbask.fsAskGpId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsAskGpId() {
        return fsAskGpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbask.fsAskGpId
     *
     * @param fsAskGpId the value for tbask.fsAskGpId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsAskGpId(String fsAskGpId) {
        this.fsAskGpId = fsAskGpId == null ? null : fsAskGpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbask.fsAskName
     *
     * @return the value of tbask.fsAskName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsAskName() {
        return fsAskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbask.fsAskName
     *
     * @param fsAskName the value for tbask.fsAskName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsAskName(String fsAskName) {
        this.fsAskName = fsAskName == null ? null : fsAskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbask.fdAddPrice
     *
     * @return the value of tbask.fdAddPrice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdAddPrice() {
        return fdAddPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbask.fdAddPrice
     *
     * @param fdAddPrice the value for tbask.fdAddPrice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdAddPrice(BigDecimal fdAddPrice) {
        this.fdAddPrice = fdAddPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbask.fsUpdateTime
     *
     * @return the value of tbask.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbask.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbask.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbask.fsUpdateUserId
     *
     * @return the value of tbask.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbask.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbask.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbask.fsUpdateUserName
     *
     * @return the value of tbask.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbask.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbask.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbask.fiItemCd
     *
     * @return the value of tbask.fiItemCd
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiItemCd() {
        return fiItemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbask.fiItemCd
     *
     * @param fiItemCd the value for tbask.fiItemCd
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiItemCd(Integer fiItemCd) {
        this.fiItemCd = fiItemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbask.fiStatus
     *
     * @return the value of tbask.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbask.fiStatus
     *
     * @param fiStatus the value for tbask.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }
}