package com.pos.entity;

public class Tbaskgp extends TbaskgpKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbaskgp.fsAskGpName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsAskGpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbaskgp.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbaskgp.fiSortOrder
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiSortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbaskgp.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbaskgp.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbaskgp.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbaskgp.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDataKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbaskgp.fiIsSelect
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsSelect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbaskgp.fiChooseType
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiChooseType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbaskgp.fsAskGpName
     *
     * @return the value of tbaskgp.fsAskGpName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsAskGpName() {
        return fsAskGpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbaskgp.fsAskGpName
     *
     * @param fsAskGpName the value for tbaskgp.fsAskGpName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsAskGpName(String fsAskGpName) {
        this.fsAskGpName = fsAskGpName == null ? null : fsAskGpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbaskgp.fiStatus
     *
     * @return the value of tbaskgp.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbaskgp.fiStatus
     *
     * @param fiStatus the value for tbaskgp.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbaskgp.fiSortOrder
     *
     * @return the value of tbaskgp.fiSortOrder
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiSortOrder() {
        return fiSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbaskgp.fiSortOrder
     *
     * @param fiSortOrder the value for tbaskgp.fiSortOrder
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiSortOrder(Integer fiSortOrder) {
        this.fiSortOrder = fiSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbaskgp.fsUpdateTime
     *
     * @return the value of tbaskgp.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbaskgp.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbaskgp.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbaskgp.fsUpdateUserId
     *
     * @return the value of tbaskgp.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbaskgp.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbaskgp.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbaskgp.fsUpdateUserName
     *
     * @return the value of tbaskgp.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbaskgp.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbaskgp.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbaskgp.fiDataKind
     *
     * @return the value of tbaskgp.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDataKind() {
        return fiDataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbaskgp.fiDataKind
     *
     * @param fiDataKind the value for tbaskgp.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDataKind(Integer fiDataKind) {
        this.fiDataKind = fiDataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbaskgp.fiIsSelect
     *
     * @return the value of tbaskgp.fiIsSelect
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsSelect() {
        return fiIsSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbaskgp.fiIsSelect
     *
     * @param fiIsSelect the value for tbaskgp.fiIsSelect
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsSelect(Integer fiIsSelect) {
        this.fiIsSelect = fiIsSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbaskgp.fiChooseType
     *
     * @return the value of tbaskgp.fiChooseType
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiChooseType() {
        return fiChooseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbaskgp.fiChooseType
     *
     * @param fiChooseType the value for tbaskgp.fiChooseType
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiChooseType(Integer fiChooseType) {
        this.fiChooseType = fiChooseType;
    }
}