package com.pos.entity;

public class Tbbillsource extends TbbillsourceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbillsource.fsBillSourceName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsBillSourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbillsource.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbillsource.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDataKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbillsource.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbillsource.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbillsource.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbillsource.fiBillSource
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiBillSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbillsource.fiMessageNotice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiMessageNotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbillsource.fiVoiceNotice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiVoiceNotice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbillsource.fsBillSourceName
     *
     * @return the value of tbbillsource.fsBillSourceName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsBillSourceName() {
        return fsBillSourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbillsource.fsBillSourceName
     *
     * @param fsBillSourceName the value for tbbillsource.fsBillSourceName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsBillSourceName(String fsBillSourceName) {
        this.fsBillSourceName = fsBillSourceName == null ? null : fsBillSourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbillsource.fiStatus
     *
     * @return the value of tbbillsource.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbillsource.fiStatus
     *
     * @param fiStatus the value for tbbillsource.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbillsource.fiDataKind
     *
     * @return the value of tbbillsource.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDataKind() {
        return fiDataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbillsource.fiDataKind
     *
     * @param fiDataKind the value for tbbillsource.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDataKind(Integer fiDataKind) {
        this.fiDataKind = fiDataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbillsource.fsUpdateTime
     *
     * @return the value of tbbillsource.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbillsource.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbbillsource.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbillsource.fsUpdateUserId
     *
     * @return the value of tbbillsource.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbillsource.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbbillsource.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbillsource.fsUpdateUserName
     *
     * @return the value of tbbillsource.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbillsource.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbbillsource.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbillsource.fiBillSource
     *
     * @return the value of tbbillsource.fiBillSource
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiBillSource() {
        return fiBillSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbillsource.fiBillSource
     *
     * @param fiBillSource the value for tbbillsource.fiBillSource
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiBillSource(Integer fiBillSource) {
        this.fiBillSource = fiBillSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbillsource.fiMessageNotice
     *
     * @return the value of tbbillsource.fiMessageNotice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiMessageNotice() {
        return fiMessageNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbillsource.fiMessageNotice
     *
     * @param fiMessageNotice the value for tbbillsource.fiMessageNotice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiMessageNotice(Integer fiMessageNotice) {
        this.fiMessageNotice = fiMessageNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbillsource.fiVoiceNotice
     *
     * @return the value of tbbillsource.fiVoiceNotice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiVoiceNotice() {
        return fiVoiceNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbillsource.fiVoiceNotice
     *
     * @param fiVoiceNotice the value for tbbillsource.fiVoiceNotice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiVoiceNotice(Integer fiVoiceNotice) {
        this.fiVoiceNotice = fiVoiceNotice;
    }
}