package com.pos.entity;

public class Tbcusttype extends TbcusttypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcusttype.fsCustTypeName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcusttype.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcusttype.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcusttype.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcusttype.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcusttype.fsCustTypeName
     *
     * @return the value of tbcusttype.fsCustTypeName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustTypeName() {
        return fsCustTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcusttype.fsCustTypeName
     *
     * @param fsCustTypeName the value for tbcusttype.fsCustTypeName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustTypeName(String fsCustTypeName) {
        this.fsCustTypeName = fsCustTypeName == null ? null : fsCustTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcusttype.fiStatus
     *
     * @return the value of tbcusttype.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcusttype.fiStatus
     *
     * @param fiStatus the value for tbcusttype.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcusttype.fsUpdateTime
     *
     * @return the value of tbcusttype.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcusttype.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbcusttype.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcusttype.fsUpdateUserId
     *
     * @return the value of tbcusttype.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcusttype.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbcusttype.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcusttype.fsUpdateUserName
     *
     * @return the value of tbcusttype.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcusttype.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbcusttype.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}