package com.pos.entity;

public class TbcusttypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcusttype.fsCompanyGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCompanyGUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcusttype.fsCustTypeId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcusttype.fsCompanyGUID
     *
     * @return the value of tbcusttype.fsCompanyGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCompanyGUID() {
        return fsCompanyGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcusttype.fsCompanyGUID
     *
     * @param fsCompanyGUID the value for tbcusttype.fsCompanyGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCompanyGUID(String fsCompanyGUID) {
        this.fsCompanyGUID = fsCompanyGUID == null ? null : fsCompanyGUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcusttype.fsCustTypeId
     *
     * @return the value of tbcusttype.fsCustTypeId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustTypeId() {
        return fsCustTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcusttype.fsCustTypeId
     *
     * @param fsCustTypeId the value for tbcusttype.fsCustTypeId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustTypeId(String fsCustTypeId) {
        this.fsCustTypeId = fsCustTypeId == null ? null : fsCustTypeId.trim();
    }
}