package com.pos.entity;

public class Tbcust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCustGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustGUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCustCls
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCustId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCustSurId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustSurId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCustSteId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustSteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCustTypeId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCustName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCustEngName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCustEngName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsPid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsBirthDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsBirthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsSex
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsJobTitle
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsJobTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCellphonePl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCellphonePl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsTelPl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsTelPl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsEmailPl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsEmailPl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsProvinceId_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsProvinceId_Pl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCityId_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCityId_Pl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsDistrictId_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDistrictId_Pl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsAddrPl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsAddrPl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsPostal_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsPostal_Pl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCompName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCompName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCompEngName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCompEngName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsTradeId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsTradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsTelCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsTelCp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsTelCpExt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsTelCpExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsFaxCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsFaxCp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsEmailCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsEmailCp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsProvinceId_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsProvinceId_Cp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCityId_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCityId_Cp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsDistrictId_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDistrictId_Cp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsAddrCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsAddrCp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsPostal_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsPostal_Cp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsContact
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsJobTitleCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsJobTitleCt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsTelCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsTelCt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCellphoneCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCellphoneCt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsEmailCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsEmailCt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsBusiScope
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsBusiScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCelebrateDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCelebrateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCardNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fiCardSte
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiCardSte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCardFreezeDesc
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCardFreezeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fiIsVIP
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsVIP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fiPoint
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fiIsSms
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsExpArea
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsExpArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsHobby
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsHobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCareful
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCareful;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsExecutive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsExecutive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsExpendDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsExpendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCreateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsCompanyGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCompanyGUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fsVIPLvlId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsVIPLvlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcust.fiExpTag
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiExpTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCustGUID
     *
     * @return the value of tbcust.fsCustGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustGUID() {
        return fsCustGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCustGUID
     *
     * @param fsCustGUID the value for tbcust.fsCustGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustGUID(String fsCustGUID) {
        this.fsCustGUID = fsCustGUID == null ? null : fsCustGUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCustCls
     *
     * @return the value of tbcust.fsCustCls
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustCls() {
        return fsCustCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCustCls
     *
     * @param fsCustCls the value for tbcust.fsCustCls
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustCls(String fsCustCls) {
        this.fsCustCls = fsCustCls == null ? null : fsCustCls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCustId
     *
     * @return the value of tbcust.fsCustId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustId() {
        return fsCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCustId
     *
     * @param fsCustId the value for tbcust.fsCustId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustId(String fsCustId) {
        this.fsCustId = fsCustId == null ? null : fsCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCustSurId
     *
     * @return the value of tbcust.fsCustSurId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustSurId() {
        return fsCustSurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCustSurId
     *
     * @param fsCustSurId the value for tbcust.fsCustSurId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustSurId(String fsCustSurId) {
        this.fsCustSurId = fsCustSurId == null ? null : fsCustSurId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCustSteId
     *
     * @return the value of tbcust.fsCustSteId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustSteId() {
        return fsCustSteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCustSteId
     *
     * @param fsCustSteId the value for tbcust.fsCustSteId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustSteId(String fsCustSteId) {
        this.fsCustSteId = fsCustSteId == null ? null : fsCustSteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCustTypeId
     *
     * @return the value of tbcust.fsCustTypeId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustTypeId() {
        return fsCustTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCustTypeId
     *
     * @param fsCustTypeId the value for tbcust.fsCustTypeId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustTypeId(String fsCustTypeId) {
        this.fsCustTypeId = fsCustTypeId == null ? null : fsCustTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCustName
     *
     * @return the value of tbcust.fsCustName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustName() {
        return fsCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCustName
     *
     * @param fsCustName the value for tbcust.fsCustName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustName(String fsCustName) {
        this.fsCustName = fsCustName == null ? null : fsCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCustEngName
     *
     * @return the value of tbcust.fsCustEngName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCustEngName() {
        return fsCustEngName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCustEngName
     *
     * @param fsCustEngName the value for tbcust.fsCustEngName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCustEngName(String fsCustEngName) {
        this.fsCustEngName = fsCustEngName == null ? null : fsCustEngName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsPid
     *
     * @return the value of tbcust.fsPid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsPid() {
        return fsPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsPid
     *
     * @param fsPid the value for tbcust.fsPid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsPid(String fsPid) {
        this.fsPid = fsPid == null ? null : fsPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsBirthDate
     *
     * @return the value of tbcust.fsBirthDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsBirthDate() {
        return fsBirthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsBirthDate
     *
     * @param fsBirthDate the value for tbcust.fsBirthDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsBirthDate(String fsBirthDate) {
        this.fsBirthDate = fsBirthDate == null ? null : fsBirthDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsSex
     *
     * @return the value of tbcust.fsSex
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsSex() {
        return fsSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsSex
     *
     * @param fsSex the value for tbcust.fsSex
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsSex(String fsSex) {
        this.fsSex = fsSex == null ? null : fsSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsJobTitle
     *
     * @return the value of tbcust.fsJobTitle
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsJobTitle() {
        return fsJobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsJobTitle
     *
     * @param fsJobTitle the value for tbcust.fsJobTitle
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsJobTitle(String fsJobTitle) {
        this.fsJobTitle = fsJobTitle == null ? null : fsJobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCellphonePl
     *
     * @return the value of tbcust.fsCellphonePl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCellphonePl() {
        return fsCellphonePl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCellphonePl
     *
     * @param fsCellphonePl the value for tbcust.fsCellphonePl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCellphonePl(String fsCellphonePl) {
        this.fsCellphonePl = fsCellphonePl == null ? null : fsCellphonePl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsTelPl
     *
     * @return the value of tbcust.fsTelPl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsTelPl() {
        return fsTelPl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsTelPl
     *
     * @param fsTelPl the value for tbcust.fsTelPl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsTelPl(String fsTelPl) {
        this.fsTelPl = fsTelPl == null ? null : fsTelPl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsEmailPl
     *
     * @return the value of tbcust.fsEmailPl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsEmailPl() {
        return fsEmailPl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsEmailPl
     *
     * @param fsEmailPl the value for tbcust.fsEmailPl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsEmailPl(String fsEmailPl) {
        this.fsEmailPl = fsEmailPl == null ? null : fsEmailPl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsProvinceId_Pl
     *
     * @return the value of tbcust.fsProvinceId_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsProvinceId_Pl() {
        return fsProvinceId_Pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsProvinceId_Pl
     *
     * @param fsProvinceId_Pl the value for tbcust.fsProvinceId_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsProvinceId_Pl(String fsProvinceId_Pl) {
        this.fsProvinceId_Pl = fsProvinceId_Pl == null ? null : fsProvinceId_Pl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCityId_Pl
     *
     * @return the value of tbcust.fsCityId_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCityId_Pl() {
        return fsCityId_Pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCityId_Pl
     *
     * @param fsCityId_Pl the value for tbcust.fsCityId_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCityId_Pl(String fsCityId_Pl) {
        this.fsCityId_Pl = fsCityId_Pl == null ? null : fsCityId_Pl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsDistrictId_Pl
     *
     * @return the value of tbcust.fsDistrictId_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDistrictId_Pl() {
        return fsDistrictId_Pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsDistrictId_Pl
     *
     * @param fsDistrictId_Pl the value for tbcust.fsDistrictId_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDistrictId_Pl(String fsDistrictId_Pl) {
        this.fsDistrictId_Pl = fsDistrictId_Pl == null ? null : fsDistrictId_Pl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsAddrPl
     *
     * @return the value of tbcust.fsAddrPl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsAddrPl() {
        return fsAddrPl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsAddrPl
     *
     * @param fsAddrPl the value for tbcust.fsAddrPl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsAddrPl(String fsAddrPl) {
        this.fsAddrPl = fsAddrPl == null ? null : fsAddrPl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsPostal_Pl
     *
     * @return the value of tbcust.fsPostal_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsPostal_Pl() {
        return fsPostal_Pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsPostal_Pl
     *
     * @param fsPostal_Pl the value for tbcust.fsPostal_Pl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsPostal_Pl(String fsPostal_Pl) {
        this.fsPostal_Pl = fsPostal_Pl == null ? null : fsPostal_Pl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCompName
     *
     * @return the value of tbcust.fsCompName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCompName() {
        return fsCompName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCompName
     *
     * @param fsCompName the value for tbcust.fsCompName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCompName(String fsCompName) {
        this.fsCompName = fsCompName == null ? null : fsCompName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCompEngName
     *
     * @return the value of tbcust.fsCompEngName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCompEngName() {
        return fsCompEngName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCompEngName
     *
     * @param fsCompEngName the value for tbcust.fsCompEngName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCompEngName(String fsCompEngName) {
        this.fsCompEngName = fsCompEngName == null ? null : fsCompEngName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsTradeId
     *
     * @return the value of tbcust.fsTradeId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsTradeId() {
        return fsTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsTradeId
     *
     * @param fsTradeId the value for tbcust.fsTradeId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsTradeId(String fsTradeId) {
        this.fsTradeId = fsTradeId == null ? null : fsTradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsTelCp
     *
     * @return the value of tbcust.fsTelCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsTelCp() {
        return fsTelCp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsTelCp
     *
     * @param fsTelCp the value for tbcust.fsTelCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsTelCp(String fsTelCp) {
        this.fsTelCp = fsTelCp == null ? null : fsTelCp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsTelCpExt
     *
     * @return the value of tbcust.fsTelCpExt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsTelCpExt() {
        return fsTelCpExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsTelCpExt
     *
     * @param fsTelCpExt the value for tbcust.fsTelCpExt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsTelCpExt(String fsTelCpExt) {
        this.fsTelCpExt = fsTelCpExt == null ? null : fsTelCpExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsFaxCp
     *
     * @return the value of tbcust.fsFaxCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsFaxCp() {
        return fsFaxCp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsFaxCp
     *
     * @param fsFaxCp the value for tbcust.fsFaxCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsFaxCp(String fsFaxCp) {
        this.fsFaxCp = fsFaxCp == null ? null : fsFaxCp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsEmailCp
     *
     * @return the value of tbcust.fsEmailCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsEmailCp() {
        return fsEmailCp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsEmailCp
     *
     * @param fsEmailCp the value for tbcust.fsEmailCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsEmailCp(String fsEmailCp) {
        this.fsEmailCp = fsEmailCp == null ? null : fsEmailCp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsProvinceId_Cp
     *
     * @return the value of tbcust.fsProvinceId_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsProvinceId_Cp() {
        return fsProvinceId_Cp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsProvinceId_Cp
     *
     * @param fsProvinceId_Cp the value for tbcust.fsProvinceId_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsProvinceId_Cp(String fsProvinceId_Cp) {
        this.fsProvinceId_Cp = fsProvinceId_Cp == null ? null : fsProvinceId_Cp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCityId_Cp
     *
     * @return the value of tbcust.fsCityId_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCityId_Cp() {
        return fsCityId_Cp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCityId_Cp
     *
     * @param fsCityId_Cp the value for tbcust.fsCityId_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCityId_Cp(String fsCityId_Cp) {
        this.fsCityId_Cp = fsCityId_Cp == null ? null : fsCityId_Cp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsDistrictId_Cp
     *
     * @return the value of tbcust.fsDistrictId_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDistrictId_Cp() {
        return fsDistrictId_Cp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsDistrictId_Cp
     *
     * @param fsDistrictId_Cp the value for tbcust.fsDistrictId_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDistrictId_Cp(String fsDistrictId_Cp) {
        this.fsDistrictId_Cp = fsDistrictId_Cp == null ? null : fsDistrictId_Cp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsAddrCp
     *
     * @return the value of tbcust.fsAddrCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsAddrCp() {
        return fsAddrCp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsAddrCp
     *
     * @param fsAddrCp the value for tbcust.fsAddrCp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsAddrCp(String fsAddrCp) {
        this.fsAddrCp = fsAddrCp == null ? null : fsAddrCp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsPostal_Cp
     *
     * @return the value of tbcust.fsPostal_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsPostal_Cp() {
        return fsPostal_Cp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsPostal_Cp
     *
     * @param fsPostal_Cp the value for tbcust.fsPostal_Cp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsPostal_Cp(String fsPostal_Cp) {
        this.fsPostal_Cp = fsPostal_Cp == null ? null : fsPostal_Cp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsContact
     *
     * @return the value of tbcust.fsContact
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsContact() {
        return fsContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsContact
     *
     * @param fsContact the value for tbcust.fsContact
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsContact(String fsContact) {
        this.fsContact = fsContact == null ? null : fsContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsJobTitleCt
     *
     * @return the value of tbcust.fsJobTitleCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsJobTitleCt() {
        return fsJobTitleCt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsJobTitleCt
     *
     * @param fsJobTitleCt the value for tbcust.fsJobTitleCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsJobTitleCt(String fsJobTitleCt) {
        this.fsJobTitleCt = fsJobTitleCt == null ? null : fsJobTitleCt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsTelCt
     *
     * @return the value of tbcust.fsTelCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsTelCt() {
        return fsTelCt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsTelCt
     *
     * @param fsTelCt the value for tbcust.fsTelCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsTelCt(String fsTelCt) {
        this.fsTelCt = fsTelCt == null ? null : fsTelCt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCellphoneCt
     *
     * @return the value of tbcust.fsCellphoneCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCellphoneCt() {
        return fsCellphoneCt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCellphoneCt
     *
     * @param fsCellphoneCt the value for tbcust.fsCellphoneCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCellphoneCt(String fsCellphoneCt) {
        this.fsCellphoneCt = fsCellphoneCt == null ? null : fsCellphoneCt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsEmailCt
     *
     * @return the value of tbcust.fsEmailCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsEmailCt() {
        return fsEmailCt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsEmailCt
     *
     * @param fsEmailCt the value for tbcust.fsEmailCt
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsEmailCt(String fsEmailCt) {
        this.fsEmailCt = fsEmailCt == null ? null : fsEmailCt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsBusiScope
     *
     * @return the value of tbcust.fsBusiScope
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsBusiScope() {
        return fsBusiScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsBusiScope
     *
     * @param fsBusiScope the value for tbcust.fsBusiScope
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsBusiScope(String fsBusiScope) {
        this.fsBusiScope = fsBusiScope == null ? null : fsBusiScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCelebrateDate
     *
     * @return the value of tbcust.fsCelebrateDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCelebrateDate() {
        return fsCelebrateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCelebrateDate
     *
     * @param fsCelebrateDate the value for tbcust.fsCelebrateDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCelebrateDate(String fsCelebrateDate) {
        this.fsCelebrateDate = fsCelebrateDate == null ? null : fsCelebrateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCardNo
     *
     * @return the value of tbcust.fsCardNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCardNo() {
        return fsCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCardNo
     *
     * @param fsCardNo the value for tbcust.fsCardNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCardNo(String fsCardNo) {
        this.fsCardNo = fsCardNo == null ? null : fsCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fiCardSte
     *
     * @return the value of tbcust.fiCardSte
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiCardSte() {
        return fiCardSte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fiCardSte
     *
     * @param fiCardSte the value for tbcust.fiCardSte
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiCardSte(Integer fiCardSte) {
        this.fiCardSte = fiCardSte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCardFreezeDesc
     *
     * @return the value of tbcust.fsCardFreezeDesc
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCardFreezeDesc() {
        return fsCardFreezeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCardFreezeDesc
     *
     * @param fsCardFreezeDesc the value for tbcust.fsCardFreezeDesc
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCardFreezeDesc(String fsCardFreezeDesc) {
        this.fsCardFreezeDesc = fsCardFreezeDesc == null ? null : fsCardFreezeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fiIsVIP
     *
     * @return the value of tbcust.fiIsVIP
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsVIP() {
        return fiIsVIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fiIsVIP
     *
     * @param fiIsVIP the value for tbcust.fiIsVIP
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsVIP(Integer fiIsVIP) {
        this.fiIsVIP = fiIsVIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fiPoint
     *
     * @return the value of tbcust.fiPoint
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiPoint() {
        return fiPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fiPoint
     *
     * @param fiPoint the value for tbcust.fiPoint
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiPoint(Integer fiPoint) {
        this.fiPoint = fiPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fiIsSms
     *
     * @return the value of tbcust.fiIsSms
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsSms() {
        return fiIsSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fiIsSms
     *
     * @param fiIsSms the value for tbcust.fiIsSms
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsSms(Integer fiIsSms) {
        this.fiIsSms = fiIsSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsExpArea
     *
     * @return the value of tbcust.fsExpArea
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsExpArea() {
        return fsExpArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsExpArea
     *
     * @param fsExpArea the value for tbcust.fsExpArea
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsExpArea(String fsExpArea) {
        this.fsExpArea = fsExpArea == null ? null : fsExpArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsHobby
     *
     * @return the value of tbcust.fsHobby
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsHobby() {
        return fsHobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsHobby
     *
     * @param fsHobby the value for tbcust.fsHobby
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsHobby(String fsHobby) {
        this.fsHobby = fsHobby == null ? null : fsHobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCareful
     *
     * @return the value of tbcust.fsCareful
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCareful() {
        return fsCareful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCareful
     *
     * @param fsCareful the value for tbcust.fsCareful
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCareful(String fsCareful) {
        this.fsCareful = fsCareful == null ? null : fsCareful.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsExecutive
     *
     * @return the value of tbcust.fsExecutive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsExecutive() {
        return fsExecutive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsExecutive
     *
     * @param fsExecutive the value for tbcust.fsExecutive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsExecutive(String fsExecutive) {
        this.fsExecutive = fsExecutive == null ? null : fsExecutive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsExpendDate
     *
     * @return the value of tbcust.fsExpendDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsExpendDate() {
        return fsExpendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsExpendDate
     *
     * @param fsExpendDate the value for tbcust.fsExpendDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsExpendDate(String fsExpendDate) {
        this.fsExpendDate = fsExpendDate == null ? null : fsExpendDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsNote
     *
     * @return the value of tbcust.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsNote() {
        return fsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsNote
     *
     * @param fsNote the value for tbcust.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsNote(String fsNote) {
        this.fsNote = fsNote == null ? null : fsNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fiStatus
     *
     * @return the value of tbcust.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fiStatus
     *
     * @param fiStatus the value for tbcust.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCreateTime
     *
     * @return the value of tbcust.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCreateTime() {
        return fsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCreateTime
     *
     * @param fsCreateTime the value for tbcust.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCreateTime(String fsCreateTime) {
        this.fsCreateTime = fsCreateTime == null ? null : fsCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCreateUserName
     *
     * @return the value of tbcust.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCreateUserName() {
        return fsCreateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCreateUserName
     *
     * @param fsCreateUserName the value for tbcust.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCreateUserName(String fsCreateUserName) {
        this.fsCreateUserName = fsCreateUserName == null ? null : fsCreateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsUpdateTime
     *
     * @return the value of tbcust.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbcust.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsUpdateUserId
     *
     * @return the value of tbcust.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbcust.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsUpdateUserName
     *
     * @return the value of tbcust.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbcust.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsShopGUID
     *
     * @return the value of tbcust.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsShopGUID
     *
     * @param fsShopGUID the value for tbcust.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsCompanyGUID
     *
     * @return the value of tbcust.fsCompanyGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCompanyGUID() {
        return fsCompanyGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsCompanyGUID
     *
     * @param fsCompanyGUID the value for tbcust.fsCompanyGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCompanyGUID(String fsCompanyGUID) {
        this.fsCompanyGUID = fsCompanyGUID == null ? null : fsCompanyGUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fsVIPLvlId
     *
     * @return the value of tbcust.fsVIPLvlId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsVIPLvlId() {
        return fsVIPLvlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fsVIPLvlId
     *
     * @param fsVIPLvlId the value for tbcust.fsVIPLvlId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsVIPLvlId(String fsVIPLvlId) {
        this.fsVIPLvlId = fsVIPLvlId == null ? null : fsVIPLvlId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcust.fiExpTag
     *
     * @return the value of tbcust.fiExpTag
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiExpTag() {
        return fiExpTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcust.fiExpTag
     *
     * @param fiExpTag the value for tbcust.fiExpTag
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiExpTag(Integer fiExpTag) {
        this.fiExpTag = fiExpTag;
    }
}