package com.pos.entity;

import java.math.BigDecimal;

public class Tbcutmoney extends TbcutmoneyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcutmoney.fdFullmoney
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdFullmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcutmoney.fdCutmoney
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdCutmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcutmoney.fiDiscountRate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDiscountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcutmoney.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcutmoney.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcutmoney.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcutmoney.fsPaymentId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsPaymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcutmoney.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcutmoney.fdFullmoney
     *
     * @return the value of tbcutmoney.fdFullmoney
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdFullmoney() {
        return fdFullmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcutmoney.fdFullmoney
     *
     * @param fdFullmoney the value for tbcutmoney.fdFullmoney
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdFullmoney(BigDecimal fdFullmoney) {
        this.fdFullmoney = fdFullmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcutmoney.fdCutmoney
     *
     * @return the value of tbcutmoney.fdCutmoney
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdCutmoney() {
        return fdCutmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcutmoney.fdCutmoney
     *
     * @param fdCutmoney the value for tbcutmoney.fdCutmoney
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdCutmoney(BigDecimal fdCutmoney) {
        this.fdCutmoney = fdCutmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcutmoney.fiDiscountRate
     *
     * @return the value of tbcutmoney.fiDiscountRate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDiscountRate() {
        return fiDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcutmoney.fiDiscountRate
     *
     * @param fiDiscountRate the value for tbcutmoney.fiDiscountRate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDiscountRate(Integer fiDiscountRate) {
        this.fiDiscountRate = fiDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcutmoney.fsUpdateTime
     *
     * @return the value of tbcutmoney.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcutmoney.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbcutmoney.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcutmoney.fsUpdateUserId
     *
     * @return the value of tbcutmoney.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcutmoney.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbcutmoney.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcutmoney.fsUpdateUserName
     *
     * @return the value of tbcutmoney.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcutmoney.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbcutmoney.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcutmoney.fsPaymentId
     *
     * @return the value of tbcutmoney.fsPaymentId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsPaymentId() {
        return fsPaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcutmoney.fsPaymentId
     *
     * @param fsPaymentId the value for tbcutmoney.fsPaymentId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsPaymentId(String fsPaymentId) {
        this.fsPaymentId = fsPaymentId == null ? null : fsPaymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcutmoney.fiStatus
     *
     * @return the value of tbcutmoney.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcutmoney.fiStatus
     *
     * @param fiStatus the value for tbcutmoney.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }
}