package com.pos.entity;

import java.math.BigDecimal;

public class Tbdeliverer extends TbdelivererKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fsDelivererName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDelivererName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fiDeliverertype
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDeliverertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fsDeliverer
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDeliverer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fsCellphone
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fdChange
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeliverer.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fsDelivererName
     *
     * @return the value of tbdeliverer.fsDelivererName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDelivererName() {
        return fsDelivererName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fsDelivererName
     *
     * @param fsDelivererName the value for tbdeliverer.fsDelivererName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDelivererName(String fsDelivererName) {
        this.fsDelivererName = fsDelivererName == null ? null : fsDelivererName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fiDeliverertype
     *
     * @return the value of tbdeliverer.fiDeliverertype
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDeliverertype() {
        return fiDeliverertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fiDeliverertype
     *
     * @param fiDeliverertype the value for tbdeliverer.fiDeliverertype
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDeliverertype(Integer fiDeliverertype) {
        this.fiDeliverertype = fiDeliverertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fsDeliverer
     *
     * @return the value of tbdeliverer.fsDeliverer
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDeliverer() {
        return fsDeliverer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fsDeliverer
     *
     * @param fsDeliverer the value for tbdeliverer.fsDeliverer
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDeliverer(String fsDeliverer) {
        this.fsDeliverer = fsDeliverer == null ? null : fsDeliverer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fsCellphone
     *
     * @return the value of tbdeliverer.fsCellphone
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCellphone() {
        return fsCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fsCellphone
     *
     * @param fsCellphone the value for tbdeliverer.fsCellphone
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCellphone(String fsCellphone) {
        this.fsCellphone = fsCellphone == null ? null : fsCellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fdChange
     *
     * @return the value of tbdeliverer.fdChange
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdChange() {
        return fdChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fdChange
     *
     * @param fdChange the value for tbdeliverer.fdChange
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdChange(BigDecimal fdChange) {
        this.fdChange = fdChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fsNote
     *
     * @return the value of tbdeliverer.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsNote() {
        return fsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fsNote
     *
     * @param fsNote the value for tbdeliverer.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsNote(String fsNote) {
        this.fsNote = fsNote == null ? null : fsNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fiStatus
     *
     * @return the value of tbdeliverer.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fiStatus
     *
     * @param fiStatus the value for tbdeliverer.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fsUpdateTime
     *
     * @return the value of tbdeliverer.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbdeliverer.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fsUpdateUserId
     *
     * @return the value of tbdeliverer.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbdeliverer.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeliverer.fsUpdateUserName
     *
     * @return the value of tbdeliverer.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeliverer.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbdeliverer.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}