package com.pos.entity;

public class Tbdept extends TbdeptKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fsDeptName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fiDeptCls
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDeptCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fsPrinterName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsPrinterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fsPrinterName2
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsPrinterName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fiIsBackBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsBackBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fiIsHurryBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsHurryBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fiIsChangeBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsChangeBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fiIsTaskBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsTaskBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fiIsTurnBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsTurnBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fiIsOneItemCut
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsOneItemCut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fiPrintCopies
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiPrintCopies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdept.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fsDeptName
     *
     * @return the value of tbdept.fsDeptName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDeptName() {
        return fsDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fsDeptName
     *
     * @param fsDeptName the value for tbdept.fsDeptName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDeptName(String fsDeptName) {
        this.fsDeptName = fsDeptName == null ? null : fsDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fiDeptCls
     *
     * @return the value of tbdept.fiDeptCls
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDeptCls() {
        return fiDeptCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fiDeptCls
     *
     * @param fiDeptCls the value for tbdept.fiDeptCls
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDeptCls(Integer fiDeptCls) {
        this.fiDeptCls = fiDeptCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fsPrinterName
     *
     * @return the value of tbdept.fsPrinterName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsPrinterName() {
        return fsPrinterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fsPrinterName
     *
     * @param fsPrinterName the value for tbdept.fsPrinterName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsPrinterName(String fsPrinterName) {
        this.fsPrinterName = fsPrinterName == null ? null : fsPrinterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fsPrinterName2
     *
     * @return the value of tbdept.fsPrinterName2
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsPrinterName2() {
        return fsPrinterName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fsPrinterName2
     *
     * @param fsPrinterName2 the value for tbdept.fsPrinterName2
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsPrinterName2(String fsPrinterName2) {
        this.fsPrinterName2 = fsPrinterName2 == null ? null : fsPrinterName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fiIsBackBill
     *
     * @return the value of tbdept.fiIsBackBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsBackBill() {
        return fiIsBackBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fiIsBackBill
     *
     * @param fiIsBackBill the value for tbdept.fiIsBackBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsBackBill(Integer fiIsBackBill) {
        this.fiIsBackBill = fiIsBackBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fiIsHurryBill
     *
     * @return the value of tbdept.fiIsHurryBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsHurryBill() {
        return fiIsHurryBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fiIsHurryBill
     *
     * @param fiIsHurryBill the value for tbdept.fiIsHurryBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsHurryBill(Integer fiIsHurryBill) {
        this.fiIsHurryBill = fiIsHurryBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fiIsChangeBill
     *
     * @return the value of tbdept.fiIsChangeBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsChangeBill() {
        return fiIsChangeBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fiIsChangeBill
     *
     * @param fiIsChangeBill the value for tbdept.fiIsChangeBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsChangeBill(Integer fiIsChangeBill) {
        this.fiIsChangeBill = fiIsChangeBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fiIsTaskBill
     *
     * @return the value of tbdept.fiIsTaskBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsTaskBill() {
        return fiIsTaskBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fiIsTaskBill
     *
     * @param fiIsTaskBill the value for tbdept.fiIsTaskBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsTaskBill(Integer fiIsTaskBill) {
        this.fiIsTaskBill = fiIsTaskBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fiIsTurnBill
     *
     * @return the value of tbdept.fiIsTurnBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsTurnBill() {
        return fiIsTurnBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fiIsTurnBill
     *
     * @param fiIsTurnBill the value for tbdept.fiIsTurnBill
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsTurnBill(Integer fiIsTurnBill) {
        this.fiIsTurnBill = fiIsTurnBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fiIsOneItemCut
     *
     * @return the value of tbdept.fiIsOneItemCut
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsOneItemCut() {
        return fiIsOneItemCut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fiIsOneItemCut
     *
     * @param fiIsOneItemCut the value for tbdept.fiIsOneItemCut
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsOneItemCut(Integer fiIsOneItemCut) {
        this.fiIsOneItemCut = fiIsOneItemCut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fiPrintCopies
     *
     * @return the value of tbdept.fiPrintCopies
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiPrintCopies() {
        return fiPrintCopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fiPrintCopies
     *
     * @param fiPrintCopies the value for tbdept.fiPrintCopies
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiPrintCopies(Integer fiPrintCopies) {
        this.fiPrintCopies = fiPrintCopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fiStatus
     *
     * @return the value of tbdept.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fiStatus
     *
     * @param fiStatus the value for tbdept.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fsUpdateTime
     *
     * @return the value of tbdept.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbdept.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fsUpdateUserId
     *
     * @return the value of tbdept.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbdept.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdept.fsUpdateUserName
     *
     * @return the value of tbdept.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdept.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbdept.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}