package com.pos.entity;

public class Tbdiscountitem extends TbdiscountitemKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscountitem.fiDiscountRate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDiscountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscountitem.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscountitem.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscountitem.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscountitem.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscountitem.fiDiscountRate
     *
     * @return the value of tbdiscountitem.fiDiscountRate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDiscountRate() {
        return fiDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscountitem.fiDiscountRate
     *
     * @param fiDiscountRate the value for tbdiscountitem.fiDiscountRate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDiscountRate(Integer fiDiscountRate) {
        this.fiDiscountRate = fiDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscountitem.fsUpdateTime
     *
     * @return the value of tbdiscountitem.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscountitem.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbdiscountitem.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscountitem.fsUpdateUserId
     *
     * @return the value of tbdiscountitem.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscountitem.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbdiscountitem.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscountitem.fsUpdateUserName
     *
     * @return the value of tbdiscountitem.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscountitem.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbdiscountitem.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscountitem.fiStatus
     *
     * @return the value of tbdiscountitem.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscountitem.fiStatus
     *
     * @param fiStatus the value for tbdiscountitem.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }
}