package com.pos.entity;

import java.math.BigDecimal;

public class Tbdiscount extends TbdiscountKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fsDiscountName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDiscountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fiDiscountRate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDiscountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fiIsVIPUse
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsVIPUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDataKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fiVIPId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiVIPId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fiCouponId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fdDDV
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdDDV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fiDiscReason
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDiscReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fiIsEffectiveDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiIsEffectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fsStarDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsStarDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdiscount.fsEndDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fsDiscountName
     *
     * @return the value of tbdiscount.fsDiscountName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDiscountName() {
        return fsDiscountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fsDiscountName
     *
     * @param fsDiscountName the value for tbdiscount.fsDiscountName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDiscountName(String fsDiscountName) {
        this.fsDiscountName = fsDiscountName == null ? null : fsDiscountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fiDiscountRate
     *
     * @return the value of tbdiscount.fiDiscountRate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDiscountRate() {
        return fiDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fiDiscountRate
     *
     * @param fiDiscountRate the value for tbdiscount.fiDiscountRate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDiscountRate(Integer fiDiscountRate) {
        this.fiDiscountRate = fiDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fiIsVIPUse
     *
     * @return the value of tbdiscount.fiIsVIPUse
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsVIPUse() {
        return fiIsVIPUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fiIsVIPUse
     *
     * @param fiIsVIPUse the value for tbdiscount.fiIsVIPUse
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsVIPUse(Integer fiIsVIPUse) {
        this.fiIsVIPUse = fiIsVIPUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fiStatus
     *
     * @return the value of tbdiscount.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fiStatus
     *
     * @param fiStatus the value for tbdiscount.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fsUpdateTime
     *
     * @return the value of tbdiscount.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbdiscount.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fsUpdateUserId
     *
     * @return the value of tbdiscount.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbdiscount.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fsUpdateUserName
     *
     * @return the value of tbdiscount.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbdiscount.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fiDataKind
     *
     * @return the value of tbdiscount.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDataKind() {
        return fiDataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fiDataKind
     *
     * @param fiDataKind the value for tbdiscount.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDataKind(Integer fiDataKind) {
        this.fiDataKind = fiDataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fiVIPId
     *
     * @return the value of tbdiscount.fiVIPId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiVIPId() {
        return fiVIPId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fiVIPId
     *
     * @param fiVIPId the value for tbdiscount.fiVIPId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiVIPId(Integer fiVIPId) {
        this.fiVIPId = fiVIPId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fiCouponId
     *
     * @return the value of tbdiscount.fiCouponId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiCouponId() {
        return fiCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fiCouponId
     *
     * @param fiCouponId the value for tbdiscount.fiCouponId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiCouponId(Integer fiCouponId) {
        this.fiCouponId = fiCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fdDDV
     *
     * @return the value of tbdiscount.fdDDV
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdDDV() {
        return fdDDV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fdDDV
     *
     * @param fdDDV the value for tbdiscount.fdDDV
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdDDV(BigDecimal fdDDV) {
        this.fdDDV = fdDDV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fiDiscReason
     *
     * @return the value of tbdiscount.fiDiscReason
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDiscReason() {
        return fiDiscReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fiDiscReason
     *
     * @param fiDiscReason the value for tbdiscount.fiDiscReason
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDiscReason(Integer fiDiscReason) {
        this.fiDiscReason = fiDiscReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fiIsEffectiveDate
     *
     * @return the value of tbdiscount.fiIsEffectiveDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiIsEffectiveDate() {
        return fiIsEffectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fiIsEffectiveDate
     *
     * @param fiIsEffectiveDate the value for tbdiscount.fiIsEffectiveDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiIsEffectiveDate(Integer fiIsEffectiveDate) {
        this.fiIsEffectiveDate = fiIsEffectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fsStarDate
     *
     * @return the value of tbdiscount.fsStarDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsStarDate() {
        return fsStarDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fsStarDate
     *
     * @param fsStarDate the value for tbdiscount.fsStarDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsStarDate(String fsStarDate) {
        this.fsStarDate = fsStarDate == null ? null : fsStarDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdiscount.fsEndDate
     *
     * @return the value of tbdiscount.fsEndDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsEndDate() {
        return fsEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdiscount.fsEndDate
     *
     * @param fsEndDate the value for tbdiscount.fsEndDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsEndDate(String fsEndDate) {
        this.fsEndDate = fsEndDate == null ? null : fsEndDate.trim();
    }
}