package com.pos.entity;

public class Tbexpcls extends TbexpclsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbexpcls.fsExpClsName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsExpClsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbexpcls.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbexpcls.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbexpcls.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbexpcls.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbexpcls.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiDataKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbexpcls.fiSortOrder
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiSortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbexpcls.fsExpClsName
     *
     * @return the value of tbexpcls.fsExpClsName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsExpClsName() {
        return fsExpClsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbexpcls.fsExpClsName
     *
     * @param fsExpClsName the value for tbexpcls.fsExpClsName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsExpClsName(String fsExpClsName) {
        this.fsExpClsName = fsExpClsName == null ? null : fsExpClsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbexpcls.fiStatus
     *
     * @return the value of tbexpcls.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbexpcls.fiStatus
     *
     * @param fiStatus the value for tbexpcls.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbexpcls.fsUpdateTime
     *
     * @return the value of tbexpcls.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbexpcls.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbexpcls.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbexpcls.fsUpdateUserId
     *
     * @return the value of tbexpcls.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbexpcls.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbexpcls.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbexpcls.fsUpdateUserName
     *
     * @return the value of tbexpcls.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbexpcls.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbexpcls.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbexpcls.fiDataKind
     *
     * @return the value of tbexpcls.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiDataKind() {
        return fiDataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbexpcls.fiDataKind
     *
     * @param fiDataKind the value for tbexpcls.fiDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiDataKind(Integer fiDataKind) {
        this.fiDataKind = fiDataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbexpcls.fiSortOrder
     *
     * @return the value of tbexpcls.fiSortOrder
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiSortOrder() {
        return fiSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbexpcls.fiSortOrder
     *
     * @param fiSortOrder the value for tbexpcls.fiSortOrder
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiSortOrder(Integer fiSortOrder) {
        this.fiSortOrder = fiSortOrder;
    }
}