package com.pos.entity;

public class TbexpclsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbexpcls.fsExpClsId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsExpClsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbexpcls.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbexpcls.fsExpClsId
     *
     * @return the value of tbexpcls.fsExpClsId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsExpClsId() {
        return fsExpClsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbexpcls.fsExpClsId
     *
     * @param fsExpClsId the value for tbexpcls.fsExpClsId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsExpClsId(String fsExpClsId) {
        this.fsExpClsId = fsExpClsId == null ? null : fsExpClsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbexpcls.fsShopGUID
     *
     * @return the value of tbexpcls.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbexpcls.fsShopGUID
     *
     * @param fsShopGUID the value for tbexpcls.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }
}