package com.pos.entity;

public class TbhostKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbhost.fsHostId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsHostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbhost.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbhost.fsHostId
     *
     * @return the value of tbhost.fsHostId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsHostId() {
        return fsHostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbhost.fsHostId
     *
     * @param fsHostId the value for tbhost.fsHostId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsHostId(String fsHostId) {
        this.fsHostId = fsHostId == null ? null : fsHostId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbhost.fsShopGUID
     *
     * @return the value of tbhost.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbhost.fsShopGUID
     *
     * @param fsShopGUID the value for tbhost.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }
}