package com.pos.entity;

public class Tbinterfacemanage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fiId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsAPIName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsAPIName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fiAPIType
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiAPIType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fiAPILanguage
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiAPILanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fiEncryption
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiEncryption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsSecretKey
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsSecretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsAppID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsAppID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsAppIDkey
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsAppIDkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsExpiryDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsExpiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsServerAddress
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsServerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fiAccessMode
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiAccessMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsServerPort
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsServerPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsExecutionMode
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsExecutionMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsStr1
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsStr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsStr2
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsStr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsStr3
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsStr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbinterfacemanage.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fiId
     *
     * @return the value of tbinterfacemanage.fiId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiId() {
        return fiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fiId
     *
     * @param fiId the value for tbinterfacemanage.fiId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiId(Integer fiId) {
        this.fiId = fiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsShopGUID
     *
     * @return the value of tbinterfacemanage.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsShopGUID
     *
     * @param fsShopGUID the value for tbinterfacemanage.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsAPIName
     *
     * @return the value of tbinterfacemanage.fsAPIName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsAPIName() {
        return fsAPIName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsAPIName
     *
     * @param fsAPIName the value for tbinterfacemanage.fsAPIName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsAPIName(String fsAPIName) {
        this.fsAPIName = fsAPIName == null ? null : fsAPIName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fiAPIType
     *
     * @return the value of tbinterfacemanage.fiAPIType
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiAPIType() {
        return fiAPIType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fiAPIType
     *
     * @param fiAPIType the value for tbinterfacemanage.fiAPIType
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiAPIType(Integer fiAPIType) {
        this.fiAPIType = fiAPIType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fiAPILanguage
     *
     * @return the value of tbinterfacemanage.fiAPILanguage
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiAPILanguage() {
        return fiAPILanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fiAPILanguage
     *
     * @param fiAPILanguage the value for tbinterfacemanage.fiAPILanguage
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiAPILanguage(Integer fiAPILanguage) {
        this.fiAPILanguage = fiAPILanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fiEncryption
     *
     * @return the value of tbinterfacemanage.fiEncryption
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiEncryption() {
        return fiEncryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fiEncryption
     *
     * @param fiEncryption the value for tbinterfacemanage.fiEncryption
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiEncryption(Integer fiEncryption) {
        this.fiEncryption = fiEncryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsSecretKey
     *
     * @return the value of tbinterfacemanage.fsSecretKey
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsSecretKey() {
        return fsSecretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsSecretKey
     *
     * @param fsSecretKey the value for tbinterfacemanage.fsSecretKey
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsSecretKey(String fsSecretKey) {
        this.fsSecretKey = fsSecretKey == null ? null : fsSecretKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsAppID
     *
     * @return the value of tbinterfacemanage.fsAppID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsAppID() {
        return fsAppID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsAppID
     *
     * @param fsAppID the value for tbinterfacemanage.fsAppID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsAppID(String fsAppID) {
        this.fsAppID = fsAppID == null ? null : fsAppID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsAppIDkey
     *
     * @return the value of tbinterfacemanage.fsAppIDkey
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsAppIDkey() {
        return fsAppIDkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsAppIDkey
     *
     * @param fsAppIDkey the value for tbinterfacemanage.fsAppIDkey
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsAppIDkey(String fsAppIDkey) {
        this.fsAppIDkey = fsAppIDkey == null ? null : fsAppIDkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsExpiryDate
     *
     * @return the value of tbinterfacemanage.fsExpiryDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsExpiryDate() {
        return fsExpiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsExpiryDate
     *
     * @param fsExpiryDate the value for tbinterfacemanage.fsExpiryDate
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsExpiryDate(String fsExpiryDate) {
        this.fsExpiryDate = fsExpiryDate == null ? null : fsExpiryDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsServerAddress
     *
     * @return the value of tbinterfacemanage.fsServerAddress
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsServerAddress() {
        return fsServerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsServerAddress
     *
     * @param fsServerAddress the value for tbinterfacemanage.fsServerAddress
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsServerAddress(String fsServerAddress) {
        this.fsServerAddress = fsServerAddress == null ? null : fsServerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fiAccessMode
     *
     * @return the value of tbinterfacemanage.fiAccessMode
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiAccessMode() {
        return fiAccessMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fiAccessMode
     *
     * @param fiAccessMode the value for tbinterfacemanage.fiAccessMode
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiAccessMode(Integer fiAccessMode) {
        this.fiAccessMode = fiAccessMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsServerPort
     *
     * @return the value of tbinterfacemanage.fsServerPort
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsServerPort() {
        return fsServerPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsServerPort
     *
     * @param fsServerPort the value for tbinterfacemanage.fsServerPort
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsServerPort(String fsServerPort) {
        this.fsServerPort = fsServerPort == null ? null : fsServerPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsExecutionMode
     *
     * @return the value of tbinterfacemanage.fsExecutionMode
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsExecutionMode() {
        return fsExecutionMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsExecutionMode
     *
     * @param fsExecutionMode the value for tbinterfacemanage.fsExecutionMode
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsExecutionMode(String fsExecutionMode) {
        this.fsExecutionMode = fsExecutionMode == null ? null : fsExecutionMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsStr1
     *
     * @return the value of tbinterfacemanage.fsStr1
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsStr1() {
        return fsStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsStr1
     *
     * @param fsStr1 the value for tbinterfacemanage.fsStr1
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsStr1(String fsStr1) {
        this.fsStr1 = fsStr1 == null ? null : fsStr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsStr2
     *
     * @return the value of tbinterfacemanage.fsStr2
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsStr2() {
        return fsStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsStr2
     *
     * @param fsStr2 the value for tbinterfacemanage.fsStr2
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsStr2(String fsStr2) {
        this.fsStr2 = fsStr2 == null ? null : fsStr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsStr3
     *
     * @return the value of tbinterfacemanage.fsStr3
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsStr3() {
        return fsStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsStr3
     *
     * @param fsStr3 the value for tbinterfacemanage.fsStr3
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsStr3(String fsStr3) {
        this.fsStr3 = fsStr3 == null ? null : fsStr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fiStatus
     *
     * @return the value of tbinterfacemanage.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fiStatus
     *
     * @param fiStatus the value for tbinterfacemanage.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsUpdateTime
     *
     * @return the value of tbinterfacemanage.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbinterfacemanage.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsUpdateUserId
     *
     * @return the value of tbinterfacemanage.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbinterfacemanage.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbinterfacemanage.fsUpdateUserName
     *
     * @return the value of tbinterfacemanage.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbinterfacemanage.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbinterfacemanage.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}