package com.pos.entity;

import java.math.BigDecimal;

public class Tbitemchangetable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsSellNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsSellNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsMTableId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsMTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsSeq
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fiItemCd
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Long fiItemCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsItemId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsItemName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fdChangeQty
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdChangeQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsChangeReason
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsChangeReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsSellNo_new
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsSellNo_new;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsMTableId_new
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsMTableId_new;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCreateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbitemchangetable.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsSellNo
     *
     * @return the value of tbitemchangetable.fsSellNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsSellNo() {
        return fsSellNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsSellNo
     *
     * @param fsSellNo the value for tbitemchangetable.fsSellNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsSellNo(String fsSellNo) {
        this.fsSellNo = fsSellNo == null ? null : fsSellNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsMTableId
     *
     * @return the value of tbitemchangetable.fsMTableId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsMTableId() {
        return fsMTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsMTableId
     *
     * @param fsMTableId the value for tbitemchangetable.fsMTableId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsMTableId(String fsMTableId) {
        this.fsMTableId = fsMTableId == null ? null : fsMTableId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsSeq
     *
     * @return the value of tbitemchangetable.fsSeq
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsSeq() {
        return fsSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsSeq
     *
     * @param fsSeq the value for tbitemchangetable.fsSeq
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsSeq(String fsSeq) {
        this.fsSeq = fsSeq == null ? null : fsSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fiItemCd
     *
     * @return the value of tbitemchangetable.fiItemCd
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Long getFiItemCd() {
        return fiItemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fiItemCd
     *
     * @param fiItemCd the value for tbitemchangetable.fiItemCd
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiItemCd(Long fiItemCd) {
        this.fiItemCd = fiItemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsItemId
     *
     * @return the value of tbitemchangetable.fsItemId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsItemId() {
        return fsItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsItemId
     *
     * @param fsItemId the value for tbitemchangetable.fsItemId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsItemId(String fsItemId) {
        this.fsItemId = fsItemId == null ? null : fsItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsItemName
     *
     * @return the value of tbitemchangetable.fsItemName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsItemName() {
        return fsItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsItemName
     *
     * @param fsItemName the value for tbitemchangetable.fsItemName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsItemName(String fsItemName) {
        this.fsItemName = fsItemName == null ? null : fsItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fdChangeQty
     *
     * @return the value of tbitemchangetable.fdChangeQty
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdChangeQty() {
        return fdChangeQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fdChangeQty
     *
     * @param fdChangeQty the value for tbitemchangetable.fdChangeQty
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdChangeQty(BigDecimal fdChangeQty) {
        this.fdChangeQty = fdChangeQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsChangeReason
     *
     * @return the value of tbitemchangetable.fsChangeReason
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsChangeReason() {
        return fsChangeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsChangeReason
     *
     * @param fsChangeReason the value for tbitemchangetable.fsChangeReason
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsChangeReason(String fsChangeReason) {
        this.fsChangeReason = fsChangeReason == null ? null : fsChangeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsSellNo_new
     *
     * @return the value of tbitemchangetable.fsSellNo_new
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsSellNo_new() {
        return fsSellNo_new;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsSellNo_new
     *
     * @param fsSellNo_new the value for tbitemchangetable.fsSellNo_new
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsSellNo_new(String fsSellNo_new) {
        this.fsSellNo_new = fsSellNo_new == null ? null : fsSellNo_new.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsMTableId_new
     *
     * @return the value of tbitemchangetable.fsMTableId_new
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsMTableId_new() {
        return fsMTableId_new;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsMTableId_new
     *
     * @param fsMTableId_new the value for tbitemchangetable.fsMTableId_new
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsMTableId_new(String fsMTableId_new) {
        this.fsMTableId_new = fsMTableId_new == null ? null : fsMTableId_new.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsCreateTime
     *
     * @return the value of tbitemchangetable.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCreateTime() {
        return fsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsCreateTime
     *
     * @param fsCreateTime the value for tbitemchangetable.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCreateTime(String fsCreateTime) {
        this.fsCreateTime = fsCreateTime == null ? null : fsCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsCreateUserName
     *
     * @return the value of tbitemchangetable.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCreateUserName() {
        return fsCreateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsCreateUserName
     *
     * @param fsCreateUserName the value for tbitemchangetable.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCreateUserName(String fsCreateUserName) {
        this.fsCreateUserName = fsCreateUserName == null ? null : fsCreateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbitemchangetable.fsShopGUID
     *
     * @return the value of tbitemchangetable.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbitemchangetable.fsShopGUID
     *
     * @param fsShopGUID the value for tbitemchangetable.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }
}