package com.pos.entity;

import java.math.BigDecimal;

public class Tbmenuingredient extends TbmenuingredientKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fsItemName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fsItemName2
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsItemName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fiItemGroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiItemGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fsItemUnitId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsItemUnitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fdItemPrice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private BigDecimal fdItemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fsItemName
     *
     * @return the value of tbmenuingredient.fsItemName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsItemName() {
        return fsItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fsItemName
     *
     * @param fsItemName the value for tbmenuingredient.fsItemName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsItemName(String fsItemName) {
        this.fsItemName = fsItemName == null ? null : fsItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fsItemName2
     *
     * @return the value of tbmenuingredient.fsItemName2
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsItemName2() {
        return fsItemName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fsItemName2
     *
     * @param fsItemName2 the value for tbmenuingredient.fsItemName2
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsItemName2(String fsItemName2) {
        this.fsItemName2 = fsItemName2 == null ? null : fsItemName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fiItemGroupId
     *
     * @return the value of tbmenuingredient.fiItemGroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiItemGroupId() {
        return fiItemGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fiItemGroupId
     *
     * @param fiItemGroupId the value for tbmenuingredient.fiItemGroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiItemGroupId(Integer fiItemGroupId) {
        this.fiItemGroupId = fiItemGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fsItemUnitId
     *
     * @return the value of tbmenuingredient.fsItemUnitId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsItemUnitId() {
        return fsItemUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fsItemUnitId
     *
     * @param fsItemUnitId the value for tbmenuingredient.fsItemUnitId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsItemUnitId(String fsItemUnitId) {
        this.fsItemUnitId = fsItemUnitId == null ? null : fsItemUnitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fdItemPrice
     *
     * @return the value of tbmenuingredient.fdItemPrice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public BigDecimal getFdItemPrice() {
        return fdItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fdItemPrice
     *
     * @param fdItemPrice the value for tbmenuingredient.fdItemPrice
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFdItemPrice(BigDecimal fdItemPrice) {
        this.fdItemPrice = fdItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fiStatus
     *
     * @return the value of tbmenuingredient.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fiStatus
     *
     * @param fiStatus the value for tbmenuingredient.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fsUpdateTime
     *
     * @return the value of tbmenuingredient.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbmenuingredient.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fsUpdateUserId
     *
     * @return the value of tbmenuingredient.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbmenuingredient.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fsUpdateUserName
     *
     * @return the value of tbmenuingredient.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbmenuingredient.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}