package com.pos.entity;

public class Tbmenuingredientgp extends TbmenuingredientgpKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredientgp.fsGroupName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredientgp.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredientgp.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredientgp.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredientgp.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredientgp.fsGroupName
     *
     * @return the value of tbmenuingredientgp.fsGroupName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsGroupName() {
        return fsGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredientgp.fsGroupName
     *
     * @param fsGroupName the value for tbmenuingredientgp.fsGroupName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsGroupName(String fsGroupName) {
        this.fsGroupName = fsGroupName == null ? null : fsGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredientgp.fiStatus
     *
     * @return the value of tbmenuingredientgp.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredientgp.fiStatus
     *
     * @param fiStatus the value for tbmenuingredientgp.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredientgp.fsUpdateTime
     *
     * @return the value of tbmenuingredientgp.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredientgp.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbmenuingredientgp.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredientgp.fsUpdateUserId
     *
     * @return the value of tbmenuingredientgp.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredientgp.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbmenuingredientgp.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredientgp.fsUpdateUserName
     *
     * @return the value of tbmenuingredientgp.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredientgp.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbmenuingredientgp.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}