package com.pos.entity;

public class TbmenuingredientgpKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredientgp.fiItemGroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiItemGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredientgp.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredientgp.fiItemGroupId
     *
     * @return the value of tbmenuingredientgp.fiItemGroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiItemGroupId() {
        return fiItemGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredientgp.fiItemGroupId
     *
     * @param fiItemGroupId the value for tbmenuingredientgp.fiItemGroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiItemGroupId(Integer fiItemGroupId) {
        this.fiItemGroupId = fiItemGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredientgp.fsShopGUID
     *
     * @return the value of tbmenuingredientgp.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredientgp.fsShopGUID
     *
     * @param fsShopGUID the value for tbmenuingredientgp.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }
}