package com.pos.entity;

public class Tbmenuitemmuldept extends TbmenuitemmuldeptKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuitemmuldept.fiItemCd
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiItemCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuitemmuldept.fsDeptId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuitemmuldept.fsMAreaId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsMAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuitemmuldept.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuitemmuldept.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuitemmuldept.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuitemmuldept.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuitemmuldept.fiItemCd
     *
     * @return the value of tbmenuitemmuldept.fiItemCd
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiItemCd() {
        return fiItemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuitemmuldept.fiItemCd
     *
     * @param fiItemCd the value for tbmenuitemmuldept.fiItemCd
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiItemCd(Integer fiItemCd) {
        this.fiItemCd = fiItemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuitemmuldept.fsDeptId
     *
     * @return the value of tbmenuitemmuldept.fsDeptId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDeptId() {
        return fsDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuitemmuldept.fsDeptId
     *
     * @param fsDeptId the value for tbmenuitemmuldept.fsDeptId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDeptId(String fsDeptId) {
        this.fsDeptId = fsDeptId == null ? null : fsDeptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuitemmuldept.fsMAreaId
     *
     * @return the value of tbmenuitemmuldept.fsMAreaId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsMAreaId() {
        return fsMAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuitemmuldept.fsMAreaId
     *
     * @param fsMAreaId the value for tbmenuitemmuldept.fsMAreaId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsMAreaId(String fsMAreaId) {
        this.fsMAreaId = fsMAreaId == null ? null : fsMAreaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuitemmuldept.fiStatus
     *
     * @return the value of tbmenuitemmuldept.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuitemmuldept.fiStatus
     *
     * @param fiStatus the value for tbmenuitemmuldept.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuitemmuldept.fsUpdateTime
     *
     * @return the value of tbmenuitemmuldept.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuitemmuldept.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbmenuitemmuldept.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuitemmuldept.fsUpdateUserId
     *
     * @return the value of tbmenuitemmuldept.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuitemmuldept.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbmenuitemmuldept.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuitemmuldept.fsUpdateUserName
     *
     * @return the value of tbmenuitemmuldept.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuitemmuldept.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbmenuitemmuldept.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}