package com.pos.entity;

public class TbmenuingredientKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fiId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmenuingredient.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fiId
     *
     * @return the value of tbmenuingredient.fiId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiId() {
        return fiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fiId
     *
     * @param fiId the value for tbmenuingredient.fiId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiId(Integer fiId) {
        this.fiId = fiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmenuingredient.fsShopGUID
     *
     * @return the value of tbmenuingredient.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmenuingredient.fsShopGUID
     *
     * @param fsShopGUID the value for tbmenuingredient.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }
}