package com.pos.entity;

public class Tbmsection extends TbmsectionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmsection.fsMSectionName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsMSectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmsection.fsBeginTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmsection.fsEndTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmsection.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmsection.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmsection.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmsection.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmsection.fsMSectionName
     *
     * @return the value of tbmsection.fsMSectionName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsMSectionName() {
        return fsMSectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmsection.fsMSectionName
     *
     * @param fsMSectionName the value for tbmsection.fsMSectionName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsMSectionName(String fsMSectionName) {
        this.fsMSectionName = fsMSectionName == null ? null : fsMSectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmsection.fsBeginTime
     *
     * @return the value of tbmsection.fsBeginTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsBeginTime() {
        return fsBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmsection.fsBeginTime
     *
     * @param fsBeginTime the value for tbmsection.fsBeginTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsBeginTime(String fsBeginTime) {
        this.fsBeginTime = fsBeginTime == null ? null : fsBeginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmsection.fsEndTime
     *
     * @return the value of tbmsection.fsEndTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsEndTime() {
        return fsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmsection.fsEndTime
     *
     * @param fsEndTime the value for tbmsection.fsEndTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsEndTime(String fsEndTime) {
        this.fsEndTime = fsEndTime == null ? null : fsEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmsection.fiStatus
     *
     * @return the value of tbmsection.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmsection.fiStatus
     *
     * @param fiStatus the value for tbmsection.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmsection.fsUpdateTime
     *
     * @return the value of tbmsection.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmsection.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbmsection.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmsection.fsUpdateUserId
     *
     * @return the value of tbmsection.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmsection.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbmsection.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmsection.fsUpdateUserName
     *
     * @return the value of tbmsection.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmsection.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbmsection.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}