package com.pos.entity;

public class Tbmtableste extends TbmtablesteKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmtableste.fsMTableSteName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsMTableSteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmtableste.fsColor
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmtableste.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmtableste.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmtableste.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmtableste.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmtableste.fsMTableSteName
     *
     * @return the value of tbmtableste.fsMTableSteName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsMTableSteName() {
        return fsMTableSteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmtableste.fsMTableSteName
     *
     * @param fsMTableSteName the value for tbmtableste.fsMTableSteName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsMTableSteName(String fsMTableSteName) {
        this.fsMTableSteName = fsMTableSteName == null ? null : fsMTableSteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmtableste.fsColor
     *
     * @return the value of tbmtableste.fsColor
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsColor() {
        return fsColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmtableste.fsColor
     *
     * @param fsColor the value for tbmtableste.fsColor
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsColor(String fsColor) {
        this.fsColor = fsColor == null ? null : fsColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmtableste.fiStatus
     *
     * @return the value of tbmtableste.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmtableste.fiStatus
     *
     * @param fiStatus the value for tbmtableste.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmtableste.fsUpdateTime
     *
     * @return the value of tbmtableste.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmtableste.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbmtableste.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmtableste.fsUpdateUserId
     *
     * @return the value of tbmtableste.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmtableste.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbmtableste.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmtableste.fsUpdateUserName
     *
     * @return the value of tbmtableste.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmtableste.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbmtableste.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}