package com.pos.entity;

public class TbmtablesteKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmtableste.fsMTableSteId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsMTableSteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbmtableste.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmtableste.fsMTableSteId
     *
     * @return the value of tbmtableste.fsMTableSteId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsMTableSteId() {
        return fsMTableSteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmtableste.fsMTableSteId
     *
     * @param fsMTableSteId the value for tbmtableste.fsMTableSteId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsMTableSteId(String fsMTableSteId) {
        this.fsMTableSteId = fsMTableSteId == null ? null : fsMTableSteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbmtableste.fsShopGUID
     *
     * @return the value of tbmtableste.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbmtableste.fsShopGUID
     *
     * @param fsShopGUID the value for tbmtableste.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }
}