package com.pos.entity;

public class Tbparam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbparam.fsParamId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsParamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbparam.fsParamName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsParamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbparam.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbparam.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbparam.fiParamCls
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiParamCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbparam.fsFoodTradeList
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsFoodTradeList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbparam.fsParamId
     *
     * @return the value of tbparam.fsParamId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsParamId() {
        return fsParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbparam.fsParamId
     *
     * @param fsParamId the value for tbparam.fsParamId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsParamId(String fsParamId) {
        this.fsParamId = fsParamId == null ? null : fsParamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbparam.fsParamName
     *
     * @return the value of tbparam.fsParamName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsParamName() {
        return fsParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbparam.fsParamName
     *
     * @param fsParamName the value for tbparam.fsParamName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsParamName(String fsParamName) {
        this.fsParamName = fsParamName == null ? null : fsParamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbparam.fsNote
     *
     * @return the value of tbparam.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsNote() {
        return fsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbparam.fsNote
     *
     * @param fsNote the value for tbparam.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsNote(String fsNote) {
        this.fsNote = fsNote == null ? null : fsNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbparam.fsUpdateTime
     *
     * @return the value of tbparam.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbparam.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbparam.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbparam.fiParamCls
     *
     * @return the value of tbparam.fiParamCls
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiParamCls() {
        return fiParamCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbparam.fiParamCls
     *
     * @param fiParamCls the value for tbparam.fiParamCls
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiParamCls(Integer fiParamCls) {
        this.fiParamCls = fiParamCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbparam.fsFoodTradeList
     *
     * @return the value of tbparam.fsFoodTradeList
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsFoodTradeList() {
        return fsFoodTradeList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbparam.fsFoodTradeList
     *
     * @param fsFoodTradeList the value for tbparam.fsFoodTradeList
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsFoodTradeList(String fsFoodTradeList) {
        this.fsFoodTradeList = fsFoodTradeList == null ? null : fsFoodTradeList.trim();
    }
}