package com.pos.entity;

public class TbpaymentdetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpaymentdetail.fsorderid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpaymentdetail.fsshopid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsshopid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpaymentdetail.fsorderid
     *
     * @return the value of tbpaymentdetail.fsorderid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsorderid() {
        return fsorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpaymentdetail.fsorderid
     *
     * @param fsorderid the value for tbpaymentdetail.fsorderid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsorderid(String fsorderid) {
        this.fsorderid = fsorderid == null ? null : fsorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpaymentdetail.fsshopid
     *
     * @return the value of tbpaymentdetail.fsshopid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsshopid() {
        return fsshopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpaymentdetail.fsshopid
     *
     * @param fsshopid the value for tbpaymentdetail.fsshopid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsshopid(String fsshopid) {
        this.fsshopid = fsshopid == null ? null : fsshopid.trim();
    }
}