package com.pos.entity;

public class TbpaymentdetailWithBLOBs extends Tbpaymentdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpaymentdetail.fsshopname
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsshopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpaymentdetail.fsmanageshopid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsmanageshopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpaymentdetail.fssourcename
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fssourcename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpaymentdetail.fsdesc
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpaymentdetail.fsbanktype
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsbanktype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpaymentdetail.fsshopname
     *
     * @return the value of tbpaymentdetail.fsshopname
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsshopname() {
        return fsshopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpaymentdetail.fsshopname
     *
     * @param fsshopname the value for tbpaymentdetail.fsshopname
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsshopname(String fsshopname) {
        this.fsshopname = fsshopname == null ? null : fsshopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpaymentdetail.fsmanageshopid
     *
     * @return the value of tbpaymentdetail.fsmanageshopid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsmanageshopid() {
        return fsmanageshopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpaymentdetail.fsmanageshopid
     *
     * @param fsmanageshopid the value for tbpaymentdetail.fsmanageshopid
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsmanageshopid(String fsmanageshopid) {
        this.fsmanageshopid = fsmanageshopid == null ? null : fsmanageshopid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpaymentdetail.fssourcename
     *
     * @return the value of tbpaymentdetail.fssourcename
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFssourcename() {
        return fssourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpaymentdetail.fssourcename
     *
     * @param fssourcename the value for tbpaymentdetail.fssourcename
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFssourcename(String fssourcename) {
        this.fssourcename = fssourcename == null ? null : fssourcename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpaymentdetail.fsdesc
     *
     * @return the value of tbpaymentdetail.fsdesc
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsdesc() {
        return fsdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpaymentdetail.fsdesc
     *
     * @param fsdesc the value for tbpaymentdetail.fsdesc
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsdesc(String fsdesc) {
        this.fsdesc = fsdesc == null ? null : fsdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpaymentdetail.fsbanktype
     *
     * @return the value of tbpaymentdetail.fsbanktype
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsbanktype() {
        return fsbanktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpaymentdetail.fsbanktype
     *
     * @param fsbanktype the value for tbpaymentdetail.fsbanktype
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsbanktype(String fsbanktype) {
        this.fsbanktype = fsbanktype == null ? null : fsbanktype.trim();
    }
}