package com.pos.entity;

public class Tbprintprojectgp extends TbprintprojectgpKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintprojectgp.fsPrintName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsPrintName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintprojectgp.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintprojectgp.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintprojectgp.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintprojectgp.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintprojectgp.fsPrintName
     *
     * @return the value of tbprintprojectgp.fsPrintName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsPrintName() {
        return fsPrintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintprojectgp.fsPrintName
     *
     * @param fsPrintName the value for tbprintprojectgp.fsPrintName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsPrintName(String fsPrintName) {
        this.fsPrintName = fsPrintName == null ? null : fsPrintName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintprojectgp.fiStatus
     *
     * @return the value of tbprintprojectgp.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintprojectgp.fiStatus
     *
     * @param fiStatus the value for tbprintprojectgp.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintprojectgp.fsUpdateTime
     *
     * @return the value of tbprintprojectgp.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintprojectgp.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbprintprojectgp.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintprojectgp.fsUpdateUserId
     *
     * @return the value of tbprintprojectgp.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintprojectgp.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbprintprojectgp.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintprojectgp.fsUpdateUserName
     *
     * @return the value of tbprintprojectgp.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintprojectgp.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbprintprojectgp.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}