package com.pos.entity;

public class Tbprintproject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintproject.fiId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintproject.figroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer figroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintproject.fsDeptId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintproject.fsMAreaId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsMAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintproject.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintproject.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintproject.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintproject.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbprintproject.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintproject.fiId
     *
     * @return the value of tbprintproject.fiId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiId() {
        return fiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintproject.fiId
     *
     * @param fiId the value for tbprintproject.fiId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiId(Integer fiId) {
        this.fiId = fiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintproject.figroupId
     *
     * @return the value of tbprintproject.figroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFigroupId() {
        return figroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintproject.figroupId
     *
     * @param figroupId the value for tbprintproject.figroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFigroupId(Integer figroupId) {
        this.figroupId = figroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintproject.fsDeptId
     *
     * @return the value of tbprintproject.fsDeptId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDeptId() {
        return fsDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintproject.fsDeptId
     *
     * @param fsDeptId the value for tbprintproject.fsDeptId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDeptId(String fsDeptId) {
        this.fsDeptId = fsDeptId == null ? null : fsDeptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintproject.fsMAreaId
     *
     * @return the value of tbprintproject.fsMAreaId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsMAreaId() {
        return fsMAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintproject.fsMAreaId
     *
     * @param fsMAreaId the value for tbprintproject.fsMAreaId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsMAreaId(String fsMAreaId) {
        this.fsMAreaId = fsMAreaId == null ? null : fsMAreaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintproject.fiStatus
     *
     * @return the value of tbprintproject.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintproject.fiStatus
     *
     * @param fiStatus the value for tbprintproject.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintproject.fsShopGUID
     *
     * @return the value of tbprintproject.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintproject.fsShopGUID
     *
     * @param fsShopGUID the value for tbprintproject.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintproject.fsUpdateTime
     *
     * @return the value of tbprintproject.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintproject.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbprintproject.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintproject.fsUpdateUserId
     *
     * @return the value of tbprintproject.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintproject.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbprintproject.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbprintproject.fsUpdateUserName
     *
     * @return the value of tbprintproject.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbprintproject.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbprintproject.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}