package com.pos.entity;

public class Tbrole extends TbroleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.fsRoleName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsRoleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.fsRoleName
     *
     * @return the value of tbrole.fsRoleName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsRoleName() {
        return fsRoleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.fsRoleName
     *
     * @param fsRoleName the value for tbrole.fsRoleName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsRoleName(String fsRoleName) {
        this.fsRoleName = fsRoleName == null ? null : fsRoleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.fsUpdateTime
     *
     * @return the value of tbrole.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbrole.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.fsUpdateUserId
     *
     * @return the value of tbrole.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbrole.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.fsUpdateUserName
     *
     * @return the value of tbrole.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbrole.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.fiStatus
     *
     * @return the value of tbrole.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.fiStatus
     *
     * @param fiStatus the value for tbrole.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }
}