package com.pos.entity;

public class Tbsellhurryitem extends TbsellhurryitemKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsellhurryitem.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsellhurryitem.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCreateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsellhurryitem.fsCreateTime
     *
     * @return the value of tbsellhurryitem.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCreateTime() {
        return fsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsellhurryitem.fsCreateTime
     *
     * @param fsCreateTime the value for tbsellhurryitem.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCreateTime(String fsCreateTime) {
        this.fsCreateTime = fsCreateTime == null ? null : fsCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsellhurryitem.fsCreateUserName
     *
     * @return the value of tbsellhurryitem.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCreateUserName() {
        return fsCreateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsellhurryitem.fsCreateUserName
     *
     * @param fsCreateUserName the value for tbsellhurryitem.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCreateUserName(String fsCreateUserName) {
        this.fsCreateUserName = fsCreateUserName == null ? null : fsCreateUserName.trim();
    }
}