package com.pos.entity;

public class TbsellcheckKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsellcheck.fsCheckBillNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCheckBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsellcheck.fsSellNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsSellNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsellcheck.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsellcheck.fsCheckBillNo
     *
     * @return the value of tbsellcheck.fsCheckBillNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCheckBillNo() {
        return fsCheckBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsellcheck.fsCheckBillNo
     *
     * @param fsCheckBillNo the value for tbsellcheck.fsCheckBillNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCheckBillNo(String fsCheckBillNo) {
        this.fsCheckBillNo = fsCheckBillNo == null ? null : fsCheckBillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsellcheck.fsSellNo
     *
     * @return the value of tbsellcheck.fsSellNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsSellNo() {
        return fsSellNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsellcheck.fsSellNo
     *
     * @param fsSellNo the value for tbsellcheck.fsSellNo
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsSellNo(String fsSellNo) {
        this.fsSellNo = fsSellNo == null ? null : fsSellNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsellcheck.fsShopGUID
     *
     * @return the value of tbsellcheck.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsellcheck.fsShopGUID
     *
     * @param fsShopGUID the value for tbsellcheck.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }
}