package com.pos.entity;

public class TbshopgroupdtlKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbshopgroupdtl.fiShopGroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiShopGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbshopgroupdtl.fsCompanyGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCompanyGUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbshopgroupdtl.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbshopgroupdtl.fiShopGroupId
     *
     * @return the value of tbshopgroupdtl.fiShopGroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiShopGroupId() {
        return fiShopGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbshopgroupdtl.fiShopGroupId
     *
     * @param fiShopGroupId the value for tbshopgroupdtl.fiShopGroupId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiShopGroupId(Integer fiShopGroupId) {
        this.fiShopGroupId = fiShopGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbshopgroupdtl.fsCompanyGUID
     *
     * @return the value of tbshopgroupdtl.fsCompanyGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCompanyGUID() {
        return fsCompanyGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbshopgroupdtl.fsCompanyGUID
     *
     * @param fsCompanyGUID the value for tbshopgroupdtl.fsCompanyGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCompanyGUID(String fsCompanyGUID) {
        this.fsCompanyGUID = fsCompanyGUID == null ? null : fsCompanyGUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbshopgroupdtl.fsShopGUID
     *
     * @return the value of tbshopgroupdtl.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbshopgroupdtl.fsShopGUID
     *
     * @param fsShopGUID the value for tbshopgroupdtl.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }
}