package com.pos.entity;

public class TbshiftKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbshift.fsShiftId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShiftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbshift.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbshift.fsShiftId
     *
     * @return the value of tbshift.fsShiftId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShiftId() {
        return fsShiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbshift.fsShiftId
     *
     * @param fsShiftId the value for tbshift.fsShiftId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShiftId(String fsShiftId) {
        this.fsShiftId = fsShiftId == null ? null : fsShiftId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbshift.fsShopGUID
     *
     * @return the value of tbshift.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbshift.fsShopGUID
     *
     * @param fsShopGUID the value for tbshift.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }
}