package com.pos.entity;

public class Tbsofttype extends TbsofttypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsofttype.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private Integer fiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsofttype.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsofttype.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCreateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsofttype.fsCreateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCreateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsofttype.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsofttype.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsofttype.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsofttype.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUpdateUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsofttype.fiStatus
     *
     * @return the value of tbsofttype.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public Integer getFiStatus() {
        return fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsofttype.fiStatus
     *
     * @param fiStatus the value for tbsofttype.fiStatus
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFiStatus(Integer fiStatus) {
        this.fiStatus = fiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsofttype.fsNote
     *
     * @return the value of tbsofttype.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsNote() {
        return fsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsofttype.fsNote
     *
     * @param fsNote the value for tbsofttype.fsNote
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsNote(String fsNote) {
        this.fsNote = fsNote == null ? null : fsNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsofttype.fsCreateUserName
     *
     * @return the value of tbsofttype.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCreateUserName() {
        return fsCreateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsofttype.fsCreateUserName
     *
     * @param fsCreateUserName the value for tbsofttype.fsCreateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCreateUserName(String fsCreateUserName) {
        this.fsCreateUserName = fsCreateUserName == null ? null : fsCreateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsofttype.fsCreateUserId
     *
     * @return the value of tbsofttype.fsCreateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCreateUserId() {
        return fsCreateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsofttype.fsCreateUserId
     *
     * @param fsCreateUserId the value for tbsofttype.fsCreateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCreateUserId(String fsCreateUserId) {
        this.fsCreateUserId = fsCreateUserId == null ? null : fsCreateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsofttype.fsCreateTime
     *
     * @return the value of tbsofttype.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsCreateTime() {
        return fsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsofttype.fsCreateTime
     *
     * @param fsCreateTime the value for tbsofttype.fsCreateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsCreateTime(String fsCreateTime) {
        this.fsCreateTime = fsCreateTime == null ? null : fsCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsofttype.fsUpdateTime
     *
     * @return the value of tbsofttype.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateTime() {
        return fsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsofttype.fsUpdateTime
     *
     * @param fsUpdateTime the value for tbsofttype.fsUpdateTime
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateTime(String fsUpdateTime) {
        this.fsUpdateTime = fsUpdateTime == null ? null : fsUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsofttype.fsUpdateUserId
     *
     * @return the value of tbsofttype.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserId() {
        return fsUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsofttype.fsUpdateUserId
     *
     * @param fsUpdateUserId the value for tbsofttype.fsUpdateUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserId(String fsUpdateUserId) {
        this.fsUpdateUserId = fsUpdateUserId == null ? null : fsUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsofttype.fsUpdateUserName
     *
     * @return the value of tbsofttype.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUpdateUserName() {
        return fsUpdateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsofttype.fsUpdateUserName
     *
     * @param fsUpdateUserName the value for tbsofttype.fsUpdateUserName
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUpdateUserName(String fsUpdateUserName) {
        this.fsUpdateUserName = fsUpdateUserName == null ? null : fsUpdateUserName.trim();
    }
}