package com.pos.entity;

public class TbuserauthdataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserauthdata.fsDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDataKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserauthdata.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserauthdata.fsUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserauthdata.fsValue
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserauthdata.fsDataKind
     *
     * @return the value of tbuserauthdata.fsDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDataKind() {
        return fsDataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserauthdata.fsDataKind
     *
     * @param fsDataKind the value for tbuserauthdata.fsDataKind
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDataKind(String fsDataKind) {
        this.fsDataKind = fsDataKind == null ? null : fsDataKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserauthdata.fsShopGUID
     *
     * @return the value of tbuserauthdata.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserauthdata.fsShopGUID
     *
     * @param fsShopGUID the value for tbuserauthdata.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserauthdata.fsUserId
     *
     * @return the value of tbuserauthdata.fsUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUserId() {
        return fsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserauthdata.fsUserId
     *
     * @param fsUserId the value for tbuserauthdata.fsUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUserId(String fsUserId) {
        this.fsUserId = fsUserId == null ? null : fsUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserauthdata.fsValue
     *
     * @return the value of tbuserauthdata.fsValue
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsValue() {
        return fsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserauthdata.fsValue
     *
     * @param fsValue the value for tbuserauthdata.fsValue
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsValue(String fsValue) {
        this.fsValue = fsValue == null ? null : fsValue.trim();
    }
}