package com.pos.entity;

public class TbuserdiscountKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserdiscount.fsDiscountId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsDiscountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserdiscount.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsShopGUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserdiscount.fsUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    private String fsUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserdiscount.fsDiscountId
     *
     * @return the value of tbuserdiscount.fsDiscountId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsDiscountId() {
        return fsDiscountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserdiscount.fsDiscountId
     *
     * @param fsDiscountId the value for tbuserdiscount.fsDiscountId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsDiscountId(String fsDiscountId) {
        this.fsDiscountId = fsDiscountId == null ? null : fsDiscountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserdiscount.fsShopGUID
     *
     * @return the value of tbuserdiscount.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsShopGUID() {
        return fsShopGUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserdiscount.fsShopGUID
     *
     * @param fsShopGUID the value for tbuserdiscount.fsShopGUID
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsShopGUID(String fsShopGUID) {
        this.fsShopGUID = fsShopGUID == null ? null : fsShopGUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserdiscount.fsUserId
     *
     * @return the value of tbuserdiscount.fsUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public String getFsUserId() {
        return fsUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserdiscount.fsUserId
     *
     * @param fsUserId the value for tbuserdiscount.fsUserId
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    public void setFsUserId(String fsUserId) {
        this.fsUserId = fsUserId == null ? null : fsUserId.trim();
    }
}