package com.pos.dao;

import com.pos.entity.Apibusiness;

public interface ApibusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apibusiness
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(String fsbusinessno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apibusiness
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Apibusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apibusiness
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Apibusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apibusiness
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Apibusiness selectByPrimaryKey(String fsbusinessno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apibusiness
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Apibusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apibusiness
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Apibusiness record);
}