package com.pos.dao;

import com.pos.entity.Apipaymentdetail;
import com.pos.entity.ApipaymentdetailWithBLOBs;

public interface ApipaymentdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apipaymentdetail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(String fspayno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apipaymentdetail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(ApipaymentdetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apipaymentdetail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(ApipaymentdetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apipaymentdetail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    ApipaymentdetailWithBLOBs selectByPrimaryKey(String fspayno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apipaymentdetail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(ApipaymentdetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apipaymentdetail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ApipaymentdetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apipaymentdetail
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Apipaymentdetail record);
}