package com.pos.dao;

import com.pos.entity.Tbaskgp;
import com.pos.entity.TbaskgpKey;

public interface TbaskgpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbaskgp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbaskgpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbaskgp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbaskgp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbaskgp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbaskgp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbaskgp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbaskgp selectByPrimaryKey(TbaskgpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbaskgp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbaskgp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbaskgp
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbaskgp record);
}