package com.pos.dao;

import com.pos.entity.Tbauthority;
import com.pos.entity.TbauthorityKey;

public interface TbauthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbauthority
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbauthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbauthority
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbauthority
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbauthority
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbauthority selectByPrimaryKey(TbauthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbauthority
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbauthority
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbauthority record);
}