package com.pos.dao;

import com.pos.entity.Tbchangetable;

public interface TbchangetableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbchangetable
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbchangetable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbchangetable
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbchangetable record);
}