package com.pos.dao;

import com.pos.entity.Tbcustsur;
import com.pos.entity.TbcustsurKey;

public interface TbcustsurMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcustsur
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbcustsurKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcustsur
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbcustsur record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcustsur
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbcustsur record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcustsur
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbcustsur selectByPrimaryKey(TbcustsurKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcustsur
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbcustsur record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbcustsur
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbcustsur record);
}