package com.pos.dao;

import com.pos.entity.Tbdeliverer;
import com.pos.entity.TbdelivererKey;

public interface TbdelivererMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeliverer
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbdelivererKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeliverer
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbdeliverer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeliverer
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbdeliverer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeliverer
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbdeliverer selectByPrimaryKey(TbdelivererKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeliverer
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbdeliverer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeliverer
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbdeliverer record);
}