package com.pos.dao;

import com.pos.entity.Tbfeedback;

public interface TbfeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfeedback
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(Integer fiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfeedback
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbfeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfeedback
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbfeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfeedback
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbfeedback selectByPrimaryKey(Integer fiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfeedback
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbfeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfeedback
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbfeedback record);
}