package com.pos.dao;

import com.pos.entity.Tbfilever;

public interface TbfileverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfilever
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(String fsFileName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfilever
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbfilever record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfilever
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbfilever record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfilever
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbfilever selectByPrimaryKey(String fsFileName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfilever
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbfilever record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfilever
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbfilever record);
}