package com.pos.dao;

import com.pos.entity.Tbfoodtrade;

public interface TbfoodtradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfoodtrade
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(String fsFoodTradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfoodtrade
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbfoodtrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfoodtrade
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbfoodtrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfoodtrade
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbfoodtrade selectByPrimaryKey(String fsFoodTradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfoodtrade
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbfoodtrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbfoodtrade
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbfoodtrade record);
}