package com.pos.dao;

import com.pos.entity.Tbinterfacemanage;

public interface TbinterfacemanageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbinterfacemanage
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(Integer fiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbinterfacemanage
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbinterfacemanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbinterfacemanage
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbinterfacemanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbinterfacemanage
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbinterfacemanage selectByPrimaryKey(Integer fiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbinterfacemanage
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbinterfacemanage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbinterfacemanage
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbinterfacemanage record);
}