package com.pos.dao;

import com.pos.entity.Tbitemchangetable;

public interface TbitemchangetableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbitemchangetable
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbitemchangetable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbitemchangetable
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbitemchangetable record);
}