package com.pos.dao;

import com.pos.entity.Tbmsg;

public interface TbmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbmsg
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(Integer fiMsgNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbmsg
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbmsg
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbmsg
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbmsg selectByPrimaryKey(Integer fiMsgNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbmsg
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbmsg
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbmsg record);
}