package com.pos.dao;

import com.pos.entity.Tbprintproject;

public interface TbprintprojectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprintproject
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(Integer fiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprintproject
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbprintproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprintproject
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbprintproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprintproject
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbprintproject selectByPrimaryKey(Integer fiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprintproject
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbprintproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprintproject
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbprintproject record);
}