package com.pos.dao;

import com.pos.entity.Tbprogdtl;
import com.pos.entity.TbprogdtlKey;

public interface TbprogdtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprogdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbprogdtlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprogdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbprogdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprogdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbprogdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprogdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbprogdtl selectByPrimaryKey(TbprogdtlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprogdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbprogdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbprogdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbprogdtl record);
}