package com.pos.dao;

import com.pos.entity.Tbreporttemplet;
import com.pos.entity.TbreporttempletKey;

public interface TbreporttempletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbreporttemplet
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbreporttempletKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbreporttemplet
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbreporttemplet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbreporttemplet
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbreporttemplet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbreporttemplet
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbreporttemplet selectByPrimaryKey(TbreporttempletKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbreporttemplet
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbreporttemplet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbreporttemplet
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbreporttemplet record);
}