package com.pos.dao;

import com.pos.entity.Tbsellreceive;
import com.pos.entity.TbsellreceiveKey;

public interface TbsellreceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellreceive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbsellreceiveKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellreceive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbsellreceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellreceive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbsellreceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellreceive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbsellreceive selectByPrimaryKey(TbsellreceiveKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellreceive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbsellreceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellreceive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Tbsellreceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellreceive
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbsellreceive record);
}