package com.pos.dao;

import com.pos.entity.Tbsell;
import com.pos.entity.TbsellKey;

public interface TbsellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsell
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbsellKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsell
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbsell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsell
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbsell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsell
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbsell selectByPrimaryKey(TbsellKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsell
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbsell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsell
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbsell record);
}