package com.pos.dao;

import com.pos.entity.Tbseqno;
import com.pos.entity.TbseqnoKey;

public interface TbseqnoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbseqno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbseqnoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbseqno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbseqno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbseqno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbseqno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbseqno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbseqno selectByPrimaryKey(TbseqnoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbseqno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbseqno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbseqno
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbseqno record);
}