package com.pos.dao;

import com.pos.entity.Tbsellhurry;
import com.pos.entity.TbsellhurryKey;

public interface TbsellhurryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurry
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbsellhurryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurry
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbsellhurry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurry
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbsellhurry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurry
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbsellhurry selectByPrimaryKey(TbsellhurryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurry
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbsellhurry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurry
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbsellhurry record);
}