package com.pos.dao;

import com.pos.entity.Tbsellorderitem;
import com.pos.entity.TbsellorderitemKey;
import com.pos.entity.TbsellorderitemWithBLOBs;

public interface TbsellorderitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellorderitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbsellorderitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellorderitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(TbsellorderitemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellorderitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(TbsellorderitemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellorderitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    TbsellorderitemWithBLOBs selectByPrimaryKey(TbsellorderitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellorderitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(TbsellorderitemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellorderitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TbsellorderitemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellorderitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbsellorderitem record);
}