package com.pos.dao;

import com.pos.entity.Tbsellhurryitem;
import com.pos.entity.TbsellhurryitemKey;

public interface TbsellhurryitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurryitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbsellhurryitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurryitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbsellhurryitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurryitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbsellhurryitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurryitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbsellhurryitem selectByPrimaryKey(TbsellhurryitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurryitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbsellhurryitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsellhurryitem
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbsellhurryitem record);
}