package com.pos.dao;

import com.pos.entity.Tbshopgroupdtl;
import com.pos.entity.TbshopgroupdtlKey;

public interface TbshopgroupdtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshopgroupdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbshopgroupdtlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshopgroupdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbshopgroupdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshopgroupdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbshopgroupdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshopgroupdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbshopgroupdtl selectByPrimaryKey(TbshopgroupdtlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshopgroupdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbshopgroupdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshopgroupdtl
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbshopgroupdtl record);
}