package com.pos.dao;

import com.pos.entity.Tbshift;
import com.pos.entity.TbshiftKey;

public interface TbshiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshift
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbshiftKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshift
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbshift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshift
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbshift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshift
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbshift selectByPrimaryKey(TbshiftKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshift
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbshift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbshift
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbshift record);
}