package com.pos.dao;

import com.pos.entity.Tbtransferprn;
import com.pos.entity.TbtransferprnKey;

public interface TbtransferprnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtransferprn
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbtransferprnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtransferprn
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbtransferprn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtransferprn
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbtransferprn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtransferprn
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbtransferprn selectByPrimaryKey(TbtransferprnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtransferprn
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbtransferprn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtransferprn
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbtransferprn record);
}