package com.pos.dao;

import com.pos.entity.Tbuseroperationlog;

public interface TbuseroperationlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuseroperationlog
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuseroperationlog
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbuseroperationlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuseroperationlog
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbuseroperationlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuseroperationlog
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbuseroperationlog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuseroperationlog
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbuseroperationlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuseroperationlog
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbuseroperationlog record);
}