package com.pos.dao;

import com.pos.entity.Tbuserrole;
import com.pos.entity.TbuserroleKey;

public interface TbuserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbuserroleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbuserrole selectByPrimaryKey(TbuserroleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbuserrole record);
}