package com.pos.dao;

import com.pos.entity.Tbusermenuitemrole;
import com.pos.entity.TbusermenuitemroleKey;

public interface TbusermenuitemroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusermenuitemrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbusermenuitemroleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusermenuitemrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbusermenuitemrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusermenuitemrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbusermenuitemrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusermenuitemrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbusermenuitemrole selectByPrimaryKey(TbusermenuitemroleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusermenuitemrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbusermenuitemrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusermenuitemrole
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbusermenuitemrole record);
}