package com.pos.dao;

import com.pos.entity.Tbvipdiscount;
import com.pos.entity.TbvipdiscountKey;

public interface TbvipdiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbvipdiscount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int deleteByPrimaryKey(TbvipdiscountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbvipdiscount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insert(Tbvipdiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbvipdiscount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int insertSelective(Tbvipdiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbvipdiscount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    Tbvipdiscount selectByPrimaryKey(TbvipdiscountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbvipdiscount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKeySelective(Tbvipdiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbvipdiscount
     *
     * @mbggenerated Fri Mar 03 15:37:51 CST 2017
     */
    int updateByPrimaryKey(Tbvipdiscount record);
}